// PRD acceptance cases for src/engine.js, consolidated from the five spec groups (Articles/short queries, Punctuation/numbers,
// Spelling/authors, Titles/ISBNs, Search behaviour/sheet structure). The engine spec they test is ENGINE_SPEC.md.
// Synthetic data only: the sample rows come from the gitignored .xlsx at test time and are never copied here.
//
// HOW A SUITE USES THIS FILE
//   rows  = loadSampleRows() (test/helpers/sample.js, both tabs) followed by syntheticRows in this order, each passed through
//           toRow(r, index) so row.id = position in the combined array (the final ranking tie-break is this order).
//   ix    = CensorEngine.buildIndex(rows, { aliases })      // `aliases` below = the three CONTRACT example groups
//   res   = CensorEngine.search(c.q, ix, { enter: !!c.enter })
//   Row ids: S<n> = Sheet1 row n and O<n> = Other Materials row n (sample rows, via rowId() in test/helpers/sample.js);
//            XA*, XN*, XS*, XT*, XR*, XC* = syntheticRows ids (toRow keeps them as row.testId, which rowId() returns).
//   Every case assumes sample + synthetic rows together. When the sample .xlsx is absent (CI), a case that names only synthetic
//   rows runs on the synthetic rows alone, unless it is marked needsSample: true (its outcome depends on a sample row it does not name).
//   q is passed exactly as written: a trailing space is meaningful (the last word is then finished, not a prefix).
//
// EXPECT VOCABULARY (every listed condition must hold; lists are never exhaustive)
//   match: [ids]      each row is in res.main with tier 'match'
//   close: [ids]      each row is in res.main with tier 'close'
//   main: [ids]       each row is in res.main (either tier)
//   possible: [ids]   each row is in res.possible
//   isbnPrefix: [ids] each row is in res.isbnPrefix
//   any: [ids]        each row is in main, possible or isbnPrefix
//   absent: [ids]     no row is in main, possible or isbnPrefix
//   notMain: [ids]    no row is in res.main (it may be in possible or absent)
//   first: id         res.main[0] is this row
//   before: [[a, b]]  a and b both appear in main ++ possible, and a comes earlier
//   state: s          res.state === s ('ok' | 'empty' | 'tooShort' | 'stopwordsOnly')
//   hint: code        res.hints contains a hint with this code (keepTyping, isbnNoMatch, etAl, authorHasOthers, acronym, seriesTip)
//   reasons: [{ row, includes }]      that row's hit (in any list) has a reasons[] string containing `includes`
//   notes: [{ row, includes }]        same, on hit.notes
//   displayTitle: [{ row, equals }]   that row's hit has display.title === equals
//   maxMain: n        res.main.length <= n
//   maxTotal: n       res.main.length + res.possible.length + res.isbnPrefix.length <= n
//   enter: true on a case = the query is submitted with Enter.
//
// QUERY OVERRIDES: changes to prototype/queries.js expectations where the PRD changes behaviour, keyed by the exact q.
//   exp replaces exp and makes the query scored even when queries.js marks it uns; ok replaces ok; drop: true removes the query.
//   Regression semantics for prototype/queries.js (run on the same rows and aliases as the cases):
//     recall          every exp row is in main, possible or isbnPrefix;
//     no flood        among SAMPLE rows (S/O ids) outside exp and ok, fewer than 2 are in main and fewer than 4 in main + possible;
//     no false match  when exp is empty, no sample row outside ok is in main.
//   Synthetic rows are ignored by the two noise checks unless an override names them in exp or ok.
'use strict';

const aliases = {
  aliases: [
    { kind: 'pen name', names: ['Daniel Handler', 'Lemony Snicket'] },
    { kind: 'acronym', names: ['CKLA', 'Core Knowledge Language Arts'] },
    { kind: 'alternate title', names: ["Philosopher's Stone", "Sorcerer's Stone"] },
  ],
};

const RAW = [
  // ---- Articles and word order; short, empty and odd queries (XA) ----
  ['XA1', 'Alchemist, The: A Fable About Following Your Dream', 'Paulo Coelho', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA2', 'Petit Prince, Le', 'Antoine de Saint-Exupéry', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA3', 'Die Hard', '', '', 'UAS', 'DVD', '2024-2025', ''],
  ['XA4', 'La La Land', '', '', 'UAS', 'DVD', '2024-2025', ''],
  ['XA5', 'Up', '', '', 'UAS', 'DVD', '2024-2025', ''],
  ['XA6', 'Upside Down Magic', 'Sarah Mlynowski', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA7', 'Wizard of Oz, The', '', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA8', 'Ozone Layer Facts', '', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA9', 'Plan B', '', '', 'UAS', 'DVD', '2024-2025', ''],
  ['XA10', 'Business Plan Workbook', '', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA11', 'Malcolm X', '', '', 'UAS', 'DVD', '2024-2025', ''],
  ['XA12', 'Malcolm in the Middle', '', '', 'UAS', 'DVD', '2024-2025', ''],
  ['XA13', 'TV Guide Crosswords', '', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA14', 'Copper Kettle Lagoon', 'Wendell Pryce', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA15', 'Lagoon of the Copper Kettle', 'Ottilie Brandt', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA16', 'Dusk of the Velvet Moth', '', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA17', 'Velvet Moth Field Notes', '', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA18', 'Seashells, A-Z', '', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA19', 'The The', '', '', 'UAS', 'CD', '2024-2025', ''],
  ['XA20', 'A', 'Louis Zukofsky', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA21', 'Alquimista, El', 'Paulo Coelho', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA22', 'Miserables', 'Victor Hugo', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA23', 'Hard Rain Almanac', '', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA24', 'Frankenstein; or, The Modern Prometheus', 'Mary Shelley', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA25', 'Tin Compass, The (Revised)', 'Imogen Reyes', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA26', 'Glass Owl, The – A Winter Riddle', 'Tobias Wren', '', 'UAS', 'Book', '2024-2025', ''],
  ['XA27', 'Snowman & The Little Troll Prince, The', '', '', 'Ministry', 'Book', '2010-2011', ''],
  // ---- Punctuation, spacing and characters; numbers (XN) ----
  ['XN1', 'Twenty-One Balloons, The', 'William Pène du Bois', '', 'KES', 'Book', '2011-2012', ''],
  ['XN2', '20,000 Leagues Under the Sea', 'Jules Verne', '', 'Ministry', 'Book', '2015-2016', ''],
  ['XN3', 'Three Cups of Tea', 'Greg Mortenson', '', 'UAS', 'Book', '2016-2017', ''],
  ['XN4', 'Forty Rules of Love, The ', 'Elif Shafak', '', 'Ministry', 'Book', '2019-2020', ''],
  ['XN5', 'Henry VIII and His Six Wives', '', '', 'RS', 'Book', '2017-2018', ''],
  ['XN6', 'Wings of Fire, Books 4–6', 'Tui T. Sutherland', '', 'Ministry', 'Book', '2021-2022', ''],
  ['XN7', 'Quokka Math Practice, Grades 9–11', '', '', 'KES', 'Workbook', '2020-2021', ''],
  ['XN8', 'Zebra Phonics – Kindergarten', '', '', 'UAS', 'Workbook', '2022-2023', ''],
  ['XN9', 'Zebra Phonics – Grade 1', '', '', 'UAS', 'Workbook', '2022-2023', ''],
  ['XN10', 'Spider-Man: Into the Spider-Verse', '', '', 'RS', 'DVD', '2019-2020', ''],
  ['XN11', 'Superman Adventures Digest', '', '', 'NES', 'Book', '2012-2013', ''],
  ['XN12', 'Wrinkle in Time, A', 'Madeleine L’Engle', '', 'Ministry', 'Book', '2018-2019', ''],
  ['XN13', 'Æsop’s Fables', '', '', 'HUBS', 'Book', '2005-2006', ''],
  ['XN14', 'Pokémon Adventures', 'Hidenori Kusaka', '', 'RS', 'Book', '2020-2021', ''],
  ['XN15', 'Jane Eyre', 'Charlotte Brontë', '', 'AAG', 'Book', '2007-2008', ''],
  ['XN16', 'Strange Case of Jekyll & Hyde', 'Robert Louis Stevenson', '', 'ACA', 'Book', '2006-2007', ''],
  ['XN17', 'Where the\nCrawdads Sing ', 'Delia Owens', '', 'Ministry', 'Book', '2021-2022', ''],
  ['XN18', 'C++ for Teens', '', '', 'IAK', 'Book', '2013-2014', ''],
  ['XN19', 'Fractions 1/2 Workbook', '', '', 'GBS', 'Workbook', '2014-2015', ''],
  ['XN20', '9/11 Commission Report, The', '', '', 'Ministry', 'Book', '2005-2006', ''],
  ['XN21', 'Planet X Explorers', 'Ivo Vix', '', 'NES', 'Book', '2016-2017', ''],
  ['XN22', 'Don’t Let the Pigeon Drive the Bus!', 'Mo Willems', '', 'KES', 'Book', '2018-2019', ''],
  ['XN23', 'قِصَصُ الأَنْبِيَاءِ', '', '', 'Ministry', 'Book', '2019-2020', ''],
  ['XN24', 'Twelfth Night', 'William Shakespeare', '', 'UAS', 'Play', '2010-2011', ''],
  ['XN25', 'Five Little Monkeys', 'Eileen Christelow', '', 'AAG', 'Book', '2009-2010', ''],
  // ---- Spelling variants and typos; authors; alias lists (XS) ----
  ['XS1', 'Wolves of Quillmere Hollow, The', 'Odessa Farthingale', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS2', 'Colour of Harbour Lights, The', 'Maisie Treloar', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS3', 'Pyjama Parade at Plumtree Theatre', '', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS4', 'Organising the Grey Attic', 'Philippa Hurst', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS5', "Mr. Quimby's Lanterns", 'Tobias Wren', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS6', 'St. Ives Lighthouse Mysteries', 'Corran Pask', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS7', 'Mount Kenver Rescue', 'Ailsa Brodie', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS8', 'Hollyhock Lane Letters', 'Marguerite Kite', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS9', 'Green Kite, The', '', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS10', 'Saltmarsh Almanac', 'Ysolde K. Le Marchant', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS11', 'Orchard Clock', "Corisande L'Estrange", '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS12', 'Bog Cotton Summer', "Fintan O'Mara", '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS13', 'Birchwood Jail Sermons', 'Cornelius Abernathy Pruitt Jr.', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS14', 'Hiccup Hotel', 'Dr. Wendell Fairbrass', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS15', 'Monsoon Carnival at Kalpetta', 'Priya Nandakumar (Author), Lotte Brandvold (Illustrator)', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS16', 'Zebra Crossing Safety Handbook', 'N/A', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS17', 'Tidewater Hymnal', 'Unknown', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS18', 'Sandcastle Detectives', 'T.J. Haverstock', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS19', 'Seagull Notebooks', 'Anton Chekhov', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS20', 'Date Palm Diaries', 'Nadia Al Rashidi', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS21', "Sorcerer's Stone of Brackenmoor, The", 'Wilhelmina Crane', '', 'Ministry', 'Book', '2024-2025', ''],
  ['XS22', 'NGSS Pathways Lab Manual', '', '', 'Ministry', 'Book', '2024-2025', ''],
  // ---- Titles and ISBNs (XT) ----
  ['XT1', 'Starfall Rangers Series', 'Odile Brancroft', '', 'UAS', 'Book', '2021-2022', ''],
  ['XT2', 'Starfall Rangers: The Ember Gate', 'Odile Brancroft', '', 'GBS', 'Book', '2019-2020', ''],
  ['XT3', 'Wrenfield Quartet Box Set', '', '', 'RS', 'Book', '2018-2019', ''],
  ['XT4', 'Skyfarer', 'Sigrun Halvorsen', '', 'IAK', 'Book', '2022-2023', ''],
  ['XT5', 'The Velvet Quarry', 'Imre Kallas', '', 'KES', 'Book', '2010-2011', ''],
  ['XT6', 'Velvet Quarry', 'Imre Kallas', '', 'Ministry', 'Book', '2020-2021', ''],
  ['XT7', 'Velvet Quarry, The', 'Kallas, Imre', '', 'UAS', 'Book', '2015-2016', ''],
  ['XT8', "Quentin Ashby and the Philosopher's Lantern", 'Oona Sefton', '', 'NES', 'Book', '2012-2013', ''],
  ['XT9', 'Lighthouse of Salt', 'Ilse Brandvold', '306406152', 'HUBS', 'Book', '2023-2024', ''],
  ['XT10', 'Juniper Almanac', 'Teodor Vasko', '9781234567897 / 0-9752298-0-X', 'UAS', 'Book', '2024-2025', ''],
  ['XT11', 'Pellucid Harbor', '', 'Not available', 'GBS', 'Book', '2016-2017', ''],
  ['XT12', 'Tamarind Atlas', '', '9.79889E+12', 'AAG', 'Book', '2025-2026', ''],
  ['XT13', 'Quayside Ledger', 'Bram Okonkwo', '1320082009', 'ACA', 'Book', '2017-2018', ''],
  // ---- Search behaviour, sheet structure, deliberately not solved (XR) ----
  ['XR1', 'Zephyrine Almanac+4:22B9:310:311', 'Odalys Pemberton', '', 'UAS', 'Book', '2019-2020', ''],
  ['XR2', "Quillon's Lantern", 'Marisol Venn', '', 'HUBS', 'Book', '2012-2013', ''],
  ['XR3', "Quillon's Lantern, The", 'Venn, Marisol', '', 'Ministry', 'Book', '2020-2021', ''],
  ['XR4', "Quillon's Lantern Sketchbook", '', '', 'Ministry', 'Book', '2021-2022', ''],
  ['XR5', "Quillon's Lantern", 'Tobias Wren', '', 'KES', 'DVD', '2015-2016', ''],
  ['XR6', 'مزرعة الحيوان', 'جورج أورويل', '', 'Ministry', 'Book', '2022-2023', ''],
  ['XR7', 'Marzipan Lighthouse', '', '', 'AAG', 'Book', '2016-2017', ''],
  ['XR8', 'Lighthouse of Marzipan Dreams', '', '', 'AAG', 'Book', '2016-2017', ''],
  ['XR9', 'Marzipan Lighthouse Chronicles', '', '', 'AAG', 'Book', '2016-2017', ''],
  ['XR10', 'Quiet Meadows', 'Harriet Juniper', '', 'NES', 'Book', '2011-2012', ''],
  ['XR11', 'Juniper Island Summers', '', '', 'NES', 'Book', '2011-2012', ''],
  ['XR12', 'Copper Kettle Ballads', '', '', 'RS', 'Book', '2013-2014', ''],
  ['XR13', 'Copper Kettle Ballads Revisited', '', '', 'RS', 'DVD', '2013-2014', ''],
  // ---- Added by the consolidation (XC): pins resolved conflicts ----
  ['XC1', 'Wren, The', 'Hester Moss', '', 'NES', 'Book', '2019-2020', ''],
];

const syntheticRows = RAW.map(([id, title, author, isbn, bannedBy, type, year, memo], n) => (
  { id, tab: 'Synthetic', row: 1001 + n, title, author, isbn, bannedBy, type, year, memo }));

const LONG1 = 'The 7th Knot by Kathleen Karr. A gripping mystery adventure for young readers set in Paris, where two cousins follow a trail of clues through museums, cathedrals and hidden tunnels while racing to recover a stolen family heirloom before the summer ends. Perfect for fans of puzzles, history and art. Readers who enjoyed this title also bought Fahrenheit 451 by Ray Bradbury and 1984 by George Orwell.';
const LONG2 = 'Customers who viewed this item also viewed several other popular young adult novels about growing up, friendship, family secrets and courage, including many award winners chosen by teachers and librarians across the country, and among them was Fahrenheit 451 by Ray Bradbury, a classic that many schools still teach today in their English classes and discuss at length.';

const cases = [
  // =====================================================================================================
  // Articles and word order (AWO)
  // =====================================================================================================
  { rule: 'AWO-1', q: 'The 7th Knot', expect: { first: 'S20', match: ['S20'], displayTitle: [{ row: 'S20', equals: 'The 7th Knot' }] } },
  { rule: 'AWO-1', q: 'A 2nd Helping of Chicken Soup', expect: { first: 'S10', match: ['S10'], displayTitle: [{ row: 'S10', equals: 'A 2nd Helping of Chicken Soup' }] } },
  { rule: 'AWO-1', q: '7th Knot, The', expect: { first: 'S20', match: ['S20'] }, note: 'The query typed in sheet form is uninverted too.' },
  { rule: 'AWO-1', q: '7 habits of highly effective teens', expect: { first: 'S19', match: ['S19'], displayTitle: [{ row: 'S19', equals: 'The 7 Habits of Highly Effective Teens' }] } },
  { rule: 'AWO-1', q: 'the wizard of oz', expect: { first: 'XA7', match: ['XA7'], displayTitle: [{ row: 'XA7', equals: 'The Wizard of Oz' }] } },
  { rule: 'AWO-2', q: 'Series of Unfortunate Events', expect: { first: 'S21', match: ['S21'] }, note: "The sheet keeps the leading 'A'; the query omits it." },
  { rule: 'AWO-2', q: 'wide window', expect: { match: ['S21'] } },
  { rule: 'AWO-2', q: 'the 101 creepy jokes', expect: { first: 'S4', match: ['S4'] }, note: "'the' is not required although the row has no 'the'." },
  { rule: 'AWO-2', q: 'notes from the velvet moth', expect: { match: ['XA17'], notMain: ['XA16'] }, note: "'from' is ignorable (the prototype requires it and leaves XA17 in Possible)." },
  { rule: 'AWO-2', q: 'the velvet moth', expect: { main: ['XA16', 'XA17'], before: [['XA16', 'XA17']] }, note: "Both in order; matching the optional 'the' raises XA16." },
  { rule: 'AWO-3', q: 'the alchemist', expect: { first: 'XA1', match: ['XA1'], displayTitle: [{ row: 'XA1', equals: 'The Alchemist: A Fable About Following Your Dream' }] }, note: "Overrides prototype queries.js 'the alchemist' (exp [])." },
  { rule: 'AWO-3', q: 'the tin compass', expect: { match: ['XA25'], displayTitle: [{ row: 'XA25', equals: 'The Tin Compass (Revised)' }] } },
  { rule: 'AWO-3', q: 'the glass owl', expect: { match: ['XA26'], displayTitle: [{ row: 'XA26', equals: 'The Glass Owl – A Winter Riddle' }] }, note: 'The letter-range guard applies only to the article A, so "The – A Winter" still moves.' },
  { rule: 'AWO-3', q: 'alchemist fable', expect: { match: ['XA1'] } },
  { rule: 'AWO-4', q: 'le petit prince', expect: { first: 'XA2', match: ['XA2'], displayTitle: [{ row: 'XA2', equals: 'Le Petit Prince' }] } },
  { rule: 'AWO-4', q: 'petit prince', expect: { match: ['XA2'] } },
  { rule: 'AWO-4', q: 'el alquimista', expect: { match: ['XA21'], displayTitle: [{ row: 'XA21', equals: 'El Alquimista' }] } },
  { rule: 'AWO-4', q: 'les miserables', expect: { close: ['XA22'], reasons: [{ row: 'XA22', includes: 'searched without "les"' }] }, note: 'Found by the run without "les"; the one-word title needs an author word for the reverse check, so run 1 gives only Possible.' },
  { rule: 'AWO-4', q: 'die hard', expect: { first: 'XA3', match: ['XA3'], close: ['XA23'], reasons: [{ row: 'XA23', includes: 'searched without "die"' }] }, note: "'die' is never dropped: Die Hard is a Match and first; rows with 'hard' come in as Close from the run without 'die'." },
  { rule: 'AWO-4', q: 'la', expect: { main: ['XA4'], absent: ['XA8', 'XA14', 'XA15'] }, note: 'A foreign article typed alone is an ordinary 2-letter word: whole word only, no prefix into Layer/Lagoon.' },
  { rule: 'AWO-5', q: 'fahrenheit 451', expect: { close: ['S16'], reasons: [{ row: 'S16', includes: 'similar spelling: Farenheit' }] } },
  { rule: 'AWO-5', q: 'knot 7th', expect: { match: ['S20'] } },
  { rule: 'AWO-5', q: 'kettle lagoon', expect: { match: ['XA14', 'XA15'], before: [['XA14', 'XA15']] }, note: 'The in-order phrase ranks higher.' },
  { rule: 'AWO-5', q: 'lagoon copper', expect: { match: ['XA14', 'XA15'], before: [['XA15', 'XA14']] }, note: "In order once 'of the' is skipped: XA15 first (the prototype ranks XA14 first)." },
  { rule: 'AWO-5', q: 'copper kettle lagoon', expect: { first: 'XA14', match: ['XA14', 'XA15'] } },
  { rule: 'AWO-5', q: 'lagoon copper kettle', expect: { first: 'XA15', match: ['XA14', 'XA15'] }, note: 'Both titles equal the query as word sets; the in-order phrase then puts XA15 first.' },
  { rule: 'AWO-5', q: 'the little prince', expect: { notMain: ['XA27'], possible: ['XA27'], reasons: [{ row: 'XA27', includes: 'your words are apart in this title' }] }, note: 'Two of its four words, apart: another title, so Possible only.' },
  { rule: 'AWO-5', q: 'little troll prince', expect: { match: ['XA27'] }, note: 'Together (and more than half the title): a Match.' },
  { rule: 'AWO-5', q: 'snowman prince', expect: { possible: ['XA27'], notMain: ['XA27'] } },
  { rule: 'AWO-6', q: 'orwell 1984', expect: { first: 'S9', match: ['S9'], possible: ['S8'], reasons: [{ row: 'S8', includes: 'author not listed' }] } },
  { rule: 'AWO-6', q: '1984 by George Orwell', expect: { first: 'S9', match: ['S9'], possible: ['S8'] }, note: 'S8 is Possible through the missing-author rule; the prototype drops it.' },
  { rule: 'AWO-6', q: 'karr knot', expect: { match: ['S20'] } },
  { rule: 'AWO-6', q: 'knot by kathleen karr', expect: { first: 'S20', match: ['S20'] } },
  { rule: 'AWO-6', q: 'bradbury fahrenheit', expect: { close: ['S16'] } },
  { rule: 'AWO-7', q: 'the the', expect: { state: 'ok', first: 'XA19', match: ['XA19'] } },
  { rule: 'AWO-7', q: 'a', enter: true, expect: { state: 'ok', match: ['XA20'] } },
  { rule: 'AWO-7', q: 'the the the', expect: { state: 'stopwordsOnly', maxTotal: 0 } },
  { rule: 'AWO-7', q: 'the lion the witch and the wardrobe', expect: { absent: ['XA19', 'XA20'] }, note: 'All-small-word titles are excluded from the reverse check.' },
  { rule: 'AWO-7', q: 'a wrinkle in time a novel', expect: { match: ['XN12'], absent: ['XA19', 'XA20'] } },
  { rule: 'AWO-8', q: 'seashells a to z', expect: { match: ['XA18'], displayTitle: [{ row: 'XA18', equals: 'Seashells, A-Z' }] } },
  { rule: 'AWO-8', q: 'seashells a-z', expect: { match: ['XA18'] } },

  // =====================================================================================================
  // Short, empty and odd queries (SEO)
  // =====================================================================================================
  { rule: 'SEO-1', q: 'the', expect: { state: 'stopwordsOnly', maxTotal: 0 } },
  { rule: 'SEO-1', q: 'of the', expect: { state: 'stopwordsOnly', maxTotal: 0 } },
  { rule: 'SEO-1', q: 'and or', expect: { state: 'stopwordsOnly', maxTotal: 0 }, note: "The prototype searches 'or' (prefix to Orwell)." },
  { rule: 'SEO-1', q: 'from with', expect: { state: 'stopwordsOnly', maxTotal: 0 } },
  { rule: 'SEO-1', q: 'by', expect: { state: 'stopwordsOnly', maxTotal: 0 } },
  { rule: 'SEO-2', q: 'it', expect: { state: 'ok', main: ['O4'] } },
  { rule: 'SEO-2', q: 'up', expect: { match: ['XA5'], absent: ['XA6'] } },
  { rule: 'SEO-2', q: 'x', expect: { state: 'tooShort', maxTotal: 0 } },
  { rule: 'SEO-2', q: 'x', enter: true, expect: { state: 'ok', main: ['XA11'], notMain: ['XA12'] } },
  { rule: 'SEO-2', q: '   ', expect: { state: 'empty', maxTotal: 0 } },
  { rule: 'SEO-2', q: '!!!', enter: true, expect: { state: 'empty', maxTotal: 0 } },
  { rule: 'SEO-3', q: 'plan b', expect: { match: ['XA9'], notMain: ['XA10'] } },
  { rule: 'SEO-3', q: 'malcolm x', expect: { first: 'XA11', match: ['XA11'], notMain: ['XA12'] } },
  { rule: 'SEO-3', q: 'tv guide', expect: { match: ['XA13'], notMain: ['S8', 'S12'], possible: ['S8', 'S12'] } },
  { rule: 'SEO-3', q: 'ckla grade k', expect: { notMain: ['O5', 'O6', 'O7', 'O8'], possible: ['O5', 'O6', 'O7', 'O8'] }, note: 'PRD example: the prototype returned every Grade 5 row as a full match.' },
  { rule: 'SEO-3', q: 'R. L. Stine', expect: { main: ['S4'], reasons: [{ row: 'S4', includes: 'given names differ' }] }, note: 'Initials beside a matched author word are optional.' },
  { rule: 'SEO-3', q: 'creepy jokes r', expect: { notMain: ['S4'], possible: ['S4'] }, note: "'r' is beside a title word, not an author word, so it is required." },
  { rule: 'SEO-4', q: 'orw', expect: { match: ['S9'] } },
  { rule: 'SEO-4', q: 'orwel', expect: { match: ['S9'], absent: ['S8'] }, note: "Unfinished last word: a prefix hit, so Match. Contrast 'orwel ' (trailing space) under SPV-2." },
  { rule: 'SEO-4', q: 'lemony sni', expect: { match: ['S21'] } },
  { rule: 'SEO-4', q: 'wid window', expect: { notMain: ['S21'], possible: ['S21'] }, note: "Only the last word prefix-matches; the prototype prefix-matches 'wid'." },
  { rule: 'SEO-4', q: 'oz', expect: { match: ['XA7'], absent: ['XA8'] }, note: 'No prefix at 2 letters (Ozone).' },
  { rule: 'SEO-4', q: 'orwell 198', expect: { first: 'S9', match: ['S9'] }, note: 'Digits prefix-match from 3 digits.' },
  { rule: 'SEO-4', q: 'thr', expect: { main: ['XN3'] }, note: "A 3-letter consonant-only word that is still being typed prefix-matches ('Three'); short words are whole-word only elsewhere." },
  { rule: 'SEO-4', q: 'fa', expect: { state: 'ok', maxTotal: 0, hint: 'keepTyping' }, note: 'The prototype returns S15, S16 by 2-letter prefix.' },
  { rule: 'SEO-6', q: LONG1, expect: { first: 'S20', close: ['S20'], absent: ['S9', 'S16'], maxMain: 2, reasons: [{ row: 'S20', includes: 'whole listed title' }] }, note: "400 chars: truncated true; query = 'The 7th Knot by Kathleen Karr. A gripping mystery adventure for young readers set in Paris, where'. The prototype returns S20, S16, S9." },
  { rule: 'SEO-6', q: LONG2, expect: { absent: ['S16'], maxMain: 0 }, note: "369 chars: truncated true; query = 'Customers who viewed this item also viewed several other popular young adult'." },
  { rule: 'SEO-6', q: 'Classic dystopian novel about firemen burning books, widely taught in schools, sold as a paperback: Fahrenheit 451 by Ray Bradbury', expect: { close: ['S16'] }, note: '130 chars: never truncated (truncated false), even though the title comes after the 12th main word.' },
  { rule: 'SEO-7', q: 'Fahrenheit 451', enter: true, expect: { close: ['S16'] }, note: "Line 1 of the paste 'Fahrenheit 451\\n1984\\nThe 7th Knot': splitLines gives 3 lines, each searched with enter:true." },
  { rule: 'SEO-7', q: '1984', enter: true, expect: { first: 'S9', match: ['S9', 'S8'] }, note: 'Line 2 of the same paste; the prototype drops 1984 when the lines are joined.' },
  { rule: 'SEO-7', q: 'The 7th Knot', enter: true, expect: { first: 'S20', match: ['S20'] }, note: 'Line 3 of the same paste.' },
  { rule: 'SEO-8', q: 'the seventh knot', expect: { first: 'S20', match: ['S20'], reasons: [{ row: 'S20', includes: 'seventh = 7th' }] }, note: "highlights.title on 'The 7th Knot' = [[0,3],[4,7],[8,12]]." },
  { rule: 'SEO-8', q: 'grandmother stories', expect: { close: ['S5'], reasons: [{ row: 'S5', includes: 'Grand Mother' }] }, note: "highlights.title on '101 Stories of Grand Mother' = [[4,11],[15,27]]." },
  { rule: 'SEO-8', q: 'thirteen little blue envelopes', expect: { match: ['S7'], reasons: [{ row: 'S7', includes: 'thirteen = 13' }] } },
  { rule: 'SEO-10', q: 'fahrenheit 451; 7th knot', expect: { close: ['S16', 'S20'], maxMain: 2, reasons: [{ row: 'S20', includes: 'whole listed title' }] }, note: "v1: ';' is a space and this is one query; both rows via the whole-title-inside check." },
  { rule: 'SEO-10', q: 'Frankenstein; or, The Modern Prometheus', expect: { first: 'XA24', match: ['XA24'] } },
  { rule: 'SEO-10', q: 'orwell؛ 1984', expect: { first: 'S9', match: ['S9'] }, note: 'Arabic semicolon U+061B.' },
  { rule: 'SEO-10', q: 'frankenstein modern prometheus', expect: { match: ['XA24'] } },
  { rule: 'SEO-11', q: 'the phantom tollbooth', expect: { state: 'ok', maxTotal: 0 }, note: 'The UI shows the no-results text; the engine returns empty lists.' },
  { rule: 'SEO-11', q: 'animal farm orwell', expect: { notMain: ['S9', 'S8'], hint: 'authorHasOthers' }, note: "No results; 'orwell' is the surname of a listed author." },

  // =====================================================================================================
  // One normalizer; punctuation, spacing and characters (PN, PUNC)
  // =====================================================================================================
  { rule: 'PN-0', q: 'seconds', expect: { main: ['S18'], absent: ['S10'] }, note: "No chaining: the plural alternate 'second' is never read as ordinal 2." },
  { rule: 'PN-0', q: '7th Knot, The', expect: { first: 'S20', match: ['S20'] } },
  { rule: 'PUNC-1', q: 'Amplify CKLA - Unit 4', expect: { match: ['O5'], notMain: ['O6', 'O7', 'O8'] } },
  { rule: 'PUNC-1', q: 'amplify ckla – unit 4', expect: { match: ['O5'], notMain: ['O6', 'O7', 'O8'] } },
  { rule: 'PUNC-1', q: 'amplify ckla — unit 4', expect: { match: ['O5'] } },
  { rule: 'PUNC-1', q: 'amplify ckla‑unit 4', expect: { match: ['O5'] }, note: 'U+2011 non-breaking hyphen.' },
  { rule: 'PUNC-1', q: 'spider−man', expect: { match: ['XN10'] }, note: 'U+2212 minus sign used as a hyphen.' },
  { rule: 'PUNC-1', q: 'series of unfortunate events-the wide window', expect: { match: ['S21'] } },
  { rule: 'PUNC-2', q: 'aaron’s hair', expect: { first: 'S22', match: ['S22'] } },
  { rule: 'PUNC-2', q: 'aaron hair', expect: { match: ['S22'] }, note: 'Possessive stem alternate.' },
  { rule: 'PUNC-2', q: 'aaron´s hair', expect: { match: ['S22'] }, note: 'U+00B4 is unified before NFKD (the prototype folds it to "aaron s").' },
  { rule: 'PUNC-2', q: 'madeleine lengle', expect: { match: ['XN12'] }, note: 'Curly apostrophe in the sheet: L’Engle -> lengle.' },
  { rule: 'PUNC-2', q: 'engle wrinkle', expect: { match: ['XN12'] }, note: 'One-letter elision remainder.' },
  { rule: 'PUNC-2', q: 'don quixote', expect: { main: ['O5'], absent: ['XN22'] }, note: "don’t indexes 'dont' only, not 'don'; the prototype shows XN22 as Possible." },
  { rule: 'PUNC-3', q: 'world book 2001', expect: { first: 'S12', match: ['S12'] } },
  { rule: 'PUNC-3', q: 'wide window book 3', expect: { match: ['S21'] }, note: "The sheet's '-Book 3' has no space before the dash." },
  { rule: 'PUNC-3', q: 'patrons artists scholars', expect: { match: ['O7'] } },
  { rule: 'PUNC-3', q: '(the wide window)', expect: { match: ['S21'] } },
  { rule: 'PUNC-3', q: 'user guide:world book', expect: { match: ['S12'] } },
  { rule: 'PUNC-4', q: '360 & more fairy tales', expect: { first: 'S15', match: ['S15'] } },
  { rule: 'PUNC-4', q: '360 + more fairy tales', expect: { match: ['S15'] } },
  { rule: 'PUNC-4', q: 'jekyll and hyde', expect: { match: ['XN16'] }, note: "The sheet has '&'." },
  { rule: 'PUNC-4', q: 'jekyll & hyde', expect: { match: ['XN16'] } },
  { rule: 'PUNC-5', q: '10minute plays', expect: { match: ['S11'], notMain: ['S18'] }, note: 'A hyphen-joined alternate is Match, not Close.' },
  { rule: 'PUNC-5', q: '10-minute plays', expect: { match: ['S11'] } },
  { rule: 'PUNC-5', q: 'oneminute monologues', expect: { match: ['S18'] } },
  { rule: 'PUNC-5', q: 'spiderman', expect: { match: ['XN10'] } },
  { rule: 'PUNC-5', q: 'spider man', expect: { match: ['XN10'] } },
  { rule: 'PUNC-6', q: 'grandmother', expect: { close: ['S5'], reasons: [{ row: 'S5', includes: 'Grand Mother' }] }, note: "A join across a space is Close; reason 'written as two words: Grand Mother'." },
  { rule: 'PUNC-6', q: 'grand mother', expect: { match: ['S5'] } },
  { rule: 'PUNC-6', q: 'super man adventures', expect: { close: ['XN11'], reasons: [{ row: 'XN11', includes: 'written as one word: Superman' }] }, note: "Query-side join against the sheet word 'Superman'." },
  { rule: 'PUNC-6', q: 'fairytales', expect: { close: ['S15'] } },
  { rule: 'PUNC-6', q: 'blueenvelopes', expect: { close: ['S7'] } },
  { rule: 'PUNC-6', q: 'littleenvelopes', expect: { absent: ['S7'] }, note: "'Little' and 'Envelopes' aren't adjacent; the prototype's split-anywhere check returned S7." },
  { rule: 'PUNC-7', q: 'AMPLIFY CKLA  UNIT 4', expect: { match: ['O5'] } },
  { rule: 'PUNC-7', q: 'amplify ckla unit　 4', expect: { match: ['O5'] }, note: 'NBSP, thin space and ideographic space.' },
  { rule: 'PUNC-7', q: 'Fah​renheit 451', expect: { main: ['S16'] }, note: 'A zero-width space is deleted, which joins the word.' },
  { rule: 'PUNC-7', q: 'ＡＭＰＬＩＦＹ ＣＫＬＡ ＵＮＩＴ ４', expect: { match: ['O5'] } },
  { rule: 'PUNC-7', q: 'where the crawdads sing', expect: { match: ['XN17'], displayTitle: [{ row: 'XN17', equals: 'Where the Crawdads Sing' }] }, note: 'The cell has a line break, an NBSP and a trailing space; display collapses them.' },
  { rule: 'PUNC-7', q: 'the forty rules of love', expect: { first: 'XN4', match: ['XN4'], displayTitle: [{ row: 'XN4', equals: 'The Forty Rules of Love' }] }, note: "The cell is 'Forty Rules of Love,<NBSP>The ' and is trimmed before uninversion." },
  { rule: 'PUNC-8', q: 'Dąbrowski', expect: { match: ['S11'] } },
  { rule: 'PUNC-8', q: 'bronte', expect: { match: ['XN15'] } },
  { rule: 'PUNC-8', q: 'pokemon adventures', expect: { match: ['XN14'] } },
  { rule: 'PUNC-8', q: 'aesop fables', expect: { match: ['XN13'] }, note: 'æ -> ae plus the possessive stem.' },
  { rule: 'PUNC-8', q: 'قصص الانبياء', expect: { match: ['XN23'] }, note: 'Harakat and hamza marks are stripped by NFKD and mark removal.' },
  { rule: 'PUNC-8', q: 'Pokémon™ Adventures', expect: { match: ['XN14'] }, note: '™ becomes a space before NFKD (the prototype folds it to "pokemontm").' },
  { rule: 'PUNC-9', q: '"wide window"', expect: { match: ['S21'] } },
  { rule: 'PUNC-9', q: 'wide wind*', expect: { match: ['S21'] }, note: "A trailing '*' is not whitespace, so 'wind' is still being typed." },
  { rule: 'PUNC-9', q: 'orwell AND 1984', expect: { first: 'S9', match: ['S9'] } },
  { rule: 'PUNC-9', q: 'orwell OR bradbury', expect: { possible: ['S9', 'S16'], notMain: ['S9', 'S16'] }, note: "'or' is ignorable, so each row matches 1 of 2 words; the prototype returns nothing." },
  { rule: 'PUNC-9', q: 'fahrenheit 451?', expect: { main: ['S16'] } },
  { rule: 'PUNC-10', q: 'c++ for teens', expect: { first: 'XN18', match: ['XN18'], notMain: ['S11', 'S19'] }, note: 'Later rule, shipped because it is a 4-entry table. The prototype returns S11 and S19 as strong.' },
  { rule: 'PUNC-10', q: 'c++', expect: { main: ['XN18'] }, note: 'The prototype says tooShort.' },

  // =====================================================================================================
  // Numbers (NUM)
  // =====================================================================================================
  { rule: 'NUM-1', q: 'seven habits', expect: { first: 'S19', match: ['S19'] } },
  { rule: 'NUM-1', q: 'thirteen little blue envelopes', expect: { match: ['S7'] } },
  { rule: 'NUM-1', q: 'volume 1', expect: { match: ['S11'], notMain: ['S18'] }, note: 'Volume One = book1; Volume 2 is the same label with another number.' },
  { rule: 'NUM-1', q: '21 balloons', expect: { match: ['XN1'] } },
  { rule: 'NUM-1', q: 'twenty one', expect: { main: ['XN1'], notMain: ['S11'] }, note: 'A compound run is one unit (21, or both words literally); S11 has 20 and One but not the run.' },
  { rule: 'NUM-1', q: 'one', expect: { main: ['S11', 'S18', 'XN1'] }, note: "The literal word stays, so 'Twenty-One' still matches 'one'." },
  { rule: 'NUM-2', q: 'second helping of chicken soup', expect: { first: 'S10', match: ['S10'] } },
  { rule: 'NUM-2', q: 'the seventh knot', expect: { first: 'S20', match: ['S20'], notMain: ['S19'], reasons: [{ row: 'S20', includes: 'seventh = 7th' }] } },
  { rule: 'NUM-2', q: '7', enter: true, expect: { main: ['S19', 'S20'] }, note: '7th -> 7. O6 "Unit 7" is a legitimate whole-word match too.' },
  { rule: 'NUM-2', q: '12th night', expect: { match: ['XN24'] } },
  { rule: 'NUM-2', q: 'twelfth night', expect: { match: ['XN24'] } },
  { rule: 'NUM-3', q: 'nineteen eighty-four', expect: { main: ['S9'] } },
  { rule: 'NUM-3', q: 'Nineteen Eighty-Four by George Orwell', expect: { first: 'S9' } },
  { rule: 'NUM-3', q: 'twenty ten-minute plays', expect: { first: 'S11', main: ['S11'] }, note: 'Must pass through the separate numbers 20 and 10, not an invented 2010 digit join.' },
  { rule: 'NUM-3', q: 'nineteen hundred eighty four', expect: { main: ['S9'] } },
  { rule: 'NUM-4', q: 'fahrenheit four fifty-one', expect: { first: 'S16', main: ['S16'] }, note: 'Close because of the fuzzy Farenheit, so the check is main, not match.' },
  { rule: 'NUM-4', q: 'two eleven things', expect: { first: 'S13', match: ['S13'] } },
  { rule: 'NUM-4', q: 'three sixty fairy tales', expect: { match: ['S15'] } },
  { rule: 'NUM-4', q: 'five hundred nations', expect: { match: ['S17'], absent: ['XN25'] }, note: "'five hundred' is one unit (500, or both words literally); the prototype shows 'Five Little Monkeys' as Possible." },
  { rule: 'NUM-5', q: 'four', expect: { main: ['O5'], absent: ['S11', 'O4'] }, note: "'For' in S11 and O4 must not match." },
  { rule: 'NUM-5', q: 'tree', expect: { absent: ['XN3'] }, note: "'Three' is a number word and never a fuzzy target; the prototype shows XN3 as Possible." },
  { rule: 'NUM-5', q: 'fine', expect: { absent: ['XN25'] }, note: "'Five' is never a fuzzy target." },
  { rule: 'NUM-5', q: 'fire', expect: { main: ['XN6'], absent: ['XN25'] } },
  { rule: 'NUM-5', q: 'thre', expect: { main: ['XN3'] }, note: 'Last-word prefix matching still reaches number words as literal words.' },
  { rule: 'NUM-6', q: 'ninteen eighty four', expect: { main: ['S9'] }, note: 'The prototype returns nothing.' },
  { rule: 'NUM-6', q: 'fourty rules of love', expect: { first: 'XN4', match: ['XN4'] } },
  { rule: 'NUM-6', q: 'eigth grade english', expect: { match: ['O4'] }, note: "eigth -> eighth, then eighth + grade -> grade8 = 'Class - 8'. The prototype has it Possible only." },
  { rule: 'NUM-6', q: 'twentyone balloons', expect: { match: ['XN1'] } },
  { rule: 'NUM-6', q: 'nineteeneightyfour', expect: { main: ['S9'] } },
  { rule: 'NUM-6', q: 'twelth night', expect: { match: ['XN24'] }, note: 'A table hit is Match; the prototype only reaches it by fuzzy spelling.' },
  { rule: 'NUM-7', q: '60 seconds to shine volume ii', expect: { match: ['S18'] } },
  { rule: 'NUM-7', q: 'it so happened class viii', expect: { first: 'O4', match: ['O4'] } },
  { rule: 'NUM-7', q: 'henry 8', expect: { first: 'XN5', match: ['XN5'] } },
  { rule: 'NUM-7', q: 'henry the eighth', expect: { match: ['XN5'] }, note: 'The ordinal eighth and the Roman viii both reduce to 8.' },
  { rule: 'NUM-7', q: 'planet 10', expect: { notMain: ['XN21'] }, note: 'A single x is Roman only right after a label.' },
  { rule: 'NUM-8', q: 'ckla unit 5', expect: { possible: ['O5', 'O6', 'O7', 'O8'], notMain: ['O5', 'O6', 'O7', 'O8'] } },
  { rule: 'NUM-8', q: 'zebra phonics grade k', expect: { main: ['XN8'], notMain: ['XN9'] }, note: 'Grade K = kindergarten = grade0. The prototype ranks it the other way round.' },
  { rule: 'NUM-8', q: '#3', enter: true, expect: { main: ['S21'], absent: ['XN3'] }, note: "'#' before a digit is the book label; 'Three Cups' has 3 but no label." },
  { rule: 'NUM-8', q: 'book 5', expect: { main: ['XN6'], notMain: ['O5', 'O6', 'O8'] }, note: "In 'Activity Book – Grade 5' the book label and the 5 aren't paired: Possible at best. The prototype returns O5, O6, O8 as strong." },
  { rule: 'NUM-8', q: 'unfortunate events vol 3', expect: { main: ['S21'] }, note: 'vol and book share the book key; the prototype has it Possible only.' },
  { rule: 'NUM-8', q: 'book 3', expect: { first: 'S21', main: ['S21'], absent: ['S5', 'S12', 'O5'] }, note: "Flood guard: rows with 'Book' in Title, Author or Type but no book3 don't appear." },
  { rule: 'NUM-9', q: 'wings of fire book 5', expect: { match: ['XN6'], notes: [{ row: 'XN6', includes: 'Covers Books 4–6' }] } },
  { rule: 'NUM-9', q: 'wings of fire book 9', expect: { possible: ['XN6'], notMain: ['XN6'] } },
  { rule: 'NUM-9', q: 'quokka math grade 10', expect: { match: ['XN7'], notes: [{ row: 'XN7', includes: 'Covers Grades 9–11' }] } },
  { rule: 'NUM-9', q: 'quokka math grade 12', expect: { possible: ['XN7'], notMain: ['XN7'] } },
  { rule: 'NUM-9', q: 'wings of fire books 1-7', expect: { match: ['XN6'] }, note: 'A range in the query is satisfied by any overlapping pair term.' },
  { rule: 'NUM-10', q: '20000 leagues', expect: { match: ['XN2'] } },
  { rule: 'NUM-10', q: '20,000 leagues under the sea', expect: { first: 'XN2' } },
  { rule: 'NUM-10', q: 'twenty thousand leagues', expect: { match: ['XN2'] } },
  { rule: 'NUM-10', q: '20 thousand leagues', expect: { match: ['XN2'] }, note: 'Digit x word multiplier; the prototype has it Possible only.' },
  { rule: 'NUM-10', q: '20 leagues', expect: { notMain: ['XN2'] } },
  { rule: 'NUM-10', q: '20', expect: { main: ['S11'], absent: ['XN2', 'S12'] }, note: "'20,000' must not index a bare 20; the prototype returns XN2." },
  { rule: 'NUM-11', q: '13', expect: { main: ['S7'], absent: ['S8', 'O7', 'S18', 'XT13'] }, note: 'No match on the paste residue (S8), an ISBN (O7, XT13) or the Year of Banning 2012-2013 (S18).' },
  { rule: 'NUM-11', q: '200', expect: { main: ['S12'] }, note: 'Digits prefix-match from 3 digits.' },
  { rule: 'NUM-11', q: '45', expect: { absent: ['S16'] }, note: '2 digits: whole word only.' },
  { rule: 'NUM-11', q: '979', expect: { absent: ['O5', 'O6', 'O7', 'O8'] }, note: 'No ISBN prefix below 6 digits and never through the word index; the prototype returns O5–O8 as strong.' },
  { rule: 'NUM-11', q: '2010', expect: { absent: ['S11'] }, note: "'20 10-Minute' must not join into 2010." },
  { rule: 'NUM-11', q: '2008', expect: { absent: ['S7', 'S8', 'S10', 'S13', 'S14', 'S17', 'S19'] }, note: 'Year of Banning is not searched.' },
  { rule: 'NUM-12', q: 'orwell 2023/24', expect: { first: 'S9', main: ['S9'] } },
  { rule: 'NUM-12', q: 'orwell 2008-2009', expect: { main: ['S9'] }, note: 'A year range that matches no row never blocks.' },
  { rule: 'NUM-12', q: '101 2009-2010', expect: { first: 'S6', main: ['S4', 'S5', 'S6'] }, note: "Year boost: S6's Year of Banning is 2009-2010. The prototype returns nothing." },
  { rule: 'NUM-12', q: '1984 2008-2009', expect: { main: ['S9', 'S8'], before: [['S9', 'S8']] }, note: 'Whole-title equality (S9 = 1984) outranks the year boost on S8.' },
  { rule: 'NUM-12', q: 'little blue envelopes 13 2008 2009', expect: { main: ['S7'], absent: ['XT13'] }, note: 'Two years separated by a space are a year range, never an ISBN (1320082009 is XT13).' },
  { rule: 'NUM-12', q: '2008-2009', expect: { state: 'stopwordsOnly', maxTotal: 0 } },
  { rule: 'NUM-12', q: 'banned 2024-2025', expect: { state: 'ok', maxTotal: 0 }, note: "Only optional words: the question word 'banned' is promoted to required and matches no Title/Author/ISBN/Memo word." },
  { rule: 'NUM-13', q: '12', expect: { main: ['XN24'], absent: ['XN19'] }, note: '1/2 is never 12; Twelfth -> 12 is fine.' },
  { rule: 'NUM-13', q: 'fractions 1/2', expect: { match: ['XN19'] } },
  { rule: 'NUM-13', q: '9/11 report', expect: { match: ['XN20'] } },
  { rule: 'NUM-13', q: '911', expect: { main: ['XN20'], absent: ['XN7'] }, note: "'Grades 9–11' must not join into 911." },

  // =====================================================================================================
  // Spelling variants and typos (SPV)
  // =====================================================================================================
  { rule: 'SPV-1', q: 'fahrenheit 451', expect: { first: 'S16', close: ['S16'], reasons: [{ row: 'S16', includes: 'similar spelling: Farenheit' }] }, note: 'fahrenheit vs Farenheit is 1 edit (shorter word 9 letters, budget 2); 451 is exact.' },
  { rule: 'SPV-1', q: 'melvin berger', expect: { close: ['S6'], reasons: [{ row: 'S6', includes: 'similar spelling: Melvn' }] }, note: 'melvin vs Melvn: 1 insertion; the shorter word has 5 letters, so the budget is 1.' },
  { rule: 'SPV-1', q: 'morgan spurlock', expect: { close: ['S14'], absent: ['O4'], reasons: [{ row: 'S14', includes: 'similar spelling: Suprlock' }] }, note: 'Swapping two adjacent letters is one edit (OSA).' },
  { rule: 'SPV-1', q: 'fahrenhiet 451', expect: { close: ['S16'] }, note: '2 edits allowed because both words have 8+ letters.' },
  { rule: 'SPV-1', q: 'fahrenhite 451', expect: { possible: ['S16'], notMain: ['S16'] }, note: '3 edits is over budget, so only 451 matches: 1 of 2 words -> Possible.' },
  { rule: 'SPV-1', q: 'tchekhov', expect: { absent: ['XS19'] }, note: 'Neither the first nor the second letter agrees with Chekhov: a documented miss.' },
  { rule: 'SPV-2', q: 'munch', expect: { close: ['S22'], reasons: [{ row: 'S22', includes: 'similar spelling: Munsch' }] }, note: "No row has 'munch' exactly or as a prefix, so the fuzzy hit stays in the main list." },
  { rule: 'SPV-2', q: 'orwel ', expect: { first: 'S9', close: ['S9'], absent: ['S8'], reasons: [{ row: 'S9', includes: 'similar spelling: Orwell' }] }, note: 'The trailing space is intentional: the word is finished, so no prefix match; Orwell is reached by fuzzy spelling.' },
  { rule: 'SPV-2', q: 'fahren', expect: { close: ['S16'], reasons: [{ row: 'S16', includes: 'similar spelling: Farenheit' }] }, note: "The unfinished last word is within 1 edit of the start of 'farenheit'." },
  { rule: 'SPV-2', q: 'kar kathleen', expect: { possible: ['S20'], notMain: ['S20'] }, note: "'kar' is finished (not last), has 3 letters (0 edits) and never prefix-matches; the prototype puts S20 in the main list." },
  { rule: 'SPV-2', q: 'form', expect: { absent: ['S11', 'S18', 'O4'] }, note: "The budget uses the shorter word ('for', 0 edits), and small words are never fuzzy targets." },
  { rule: 'SPV-2', q: 'anonymous', expect: { absent: ['S12'] }, note: "Prototype bug: the capped prefix comparison passed 'International' (true distance 4)." },
  { rule: 'SPV-3', q: 'stine', expect: { first: 'S4', match: ['S4'], possible: ['S18'], notMain: ['S18'], reasons: [{ row: 'S18', includes: 'similar spelling: Shine' }] }, note: "'stine' exists exactly (S4), so the fuzzy-only S18 (and XS21 'Stone') go to Possible." },
  { rule: 'SPV-3', q: 'shine', expect: { match: ['S18'], possible: ['S4'], notMain: ['S4'] } },
  { rule: 'SPV-3', q: 'berjer', expect: { close: ['S6'] }, note: 'No exact or prefix hit exists anywhere, so the fuzzy hit stays in the main list.' },
  { rule: 'SPV-3', q: 'spurlock', expect: { first: 'S14', close: ['S14'], absent: ['O4'] }, note: "Flood guard: the prototype also returned O4 through Type 'Supplementary'." },
  { rule: 'SPV-3', q: 'screenplay', expect: { absent: ['O4'] }, note: 'Fuzzy matching never runs on Type or Banned By.' },
  { rule: 'SPV-4', q: 'monologue for woman', expect: { match: ['S18'] }, note: 'monologue -> monologues and woman -> women count as exact.' },
  { rule: 'SPV-4', q: 'tale fairy', expect: { match: ['S15'] }, note: "'tale' is not the last word, so no prefix; the plural alternate finds 'tales'." },
  { rule: 'SPV-4', q: 'story grand mother', expect: { match: ['S5'] }, note: 'story -> stories. The prototype gives Possible only.' },
  { rule: 'SPV-4', q: 'grandmothers stories', expect: { main: ['S5'] }, note: "The plural is stripped, then matched against the joined pair 'grandmother' (Close)." },
  { rule: 'SPV-4', q: 'wolf quillmere', expect: { match: ['XS1'] }, note: 'wolf -> wolves. The prototype gives Possible.' },
  { rule: 'SPV-4', q: 'johnsons', expect: { close: ['S7'] }, note: "Plural alternates don't apply to Author words: Johnson is reached by fuzzy spelling." },
  { rule: 'SPV-5', q: 'color of harbor lights', expect: { match: ['XS2'] }, note: '-or/-our alternates are exact (Match).' },
  { rule: 'SPV-5', q: 'pajama parade', expect: { match: ['XS3'] } },
  { rule: 'SPV-5', q: 'plumtree theater', expect: { match: ['XS3'] } },
  { rule: 'SPV-5', q: 'organizing the gray attic', expect: { match: ['XS4'] } },
  { rule: 'SPV-5', q: 'four teens', expect: { notMain: ['S11'] }, note: "'four' is a number word and never becomes 'for'." },
  { rule: 'SPV-6', q: 'mister quimbys lanterns', expect: { match: ['XS5'] } },
  { rule: 'SPV-6', q: 'saint ives lighthouse', expect: { match: ['XS6'] } },
  { rule: 'SPV-6', q: 'mt kenver rescue', expect: { match: ['XS7'] }, note: "'mt' is a required consonant-only word, satisfied through its alternate 'mount'." },
  { rule: 'SPV-6', q: 'doctor fairbrass', expect: { match: ['XS14'] } },
  { rule: 'SPV-6', q: 'st', expect: { main: ['XS6'], absent: ['S4', 'S5', 'S8'] }, note: 'Whole words only (no prefix into Stine, Stories, Study).' },
  { rule: 'SPV-7', q: 'core knowledge language arts unit 4', expect: { main: ['O5'], notMain: ['O6', 'O7', 'O8'], reasons: [{ row: 'O5', includes: 'via alias' }] }, note: 'Needs the CONTRACT aliases (exported below). queries.js marks it unsolvable.' },
  { rule: 'SPV-7', q: 'core knowledge language arts', expect: { main: ['O5', 'O6', 'O7', 'O8'], reasons: [{ row: 'O6', includes: 'via alias' }] } },
  { rule: 'SPV-7', q: 'next generation science standards', expect: { state: 'ok', maxMain: 0, hint: 'acronym' }, note: "The initials spell 'ngss', an indexed title word (XS22), and the main list is empty." },

  // =====================================================================================================
  // Authors (AUT) and alias lists (ALI)
  // =====================================================================================================
  { rule: 'AUT-1', q: 'orwell 1984', expect: { first: 'S9', match: ['S9'], possible: ['S8'], reasons: [{ row: 'S8', includes: 'author not listed' }] } },
  { rule: 'AUT-1', q: 'george orwell 1984', expect: { main: ['S9'], possible: ['S8'], reasons: [{ row: 'S8', includes: 'author not listed' }] }, note: 'The prototype misses S8 (1 of 3 words).' },
  { rule: 'AUT-1', q: 'ray bradbury 1984', expect: { possible: ['S8'], absent: ['S9'], reasons: [{ row: 'S8', includes: 'author not listed' }] }, note: "S9 has an author, so its misses aren't excused; the one-word title needs one of S9's own author words." },
  { rule: 'AUT-1', q: 'orwell', expect: { match: ['S9'], absent: ['S8'] }, note: 'Author words alone never list an authorless row.' },
  { rule: 'AUT-1', q: 'xylophone quokka 1984', expect: { absent: ['S8', 'S9'] }, note: 'The missed words are not author words, and 1 of 3 is under half.' },
  { rule: 'AUT-2', q: 'Orwell, George', expect: { first: 'S9', match: ['S9'], absent: ['S8'] } },
  { rule: 'AUT-2', q: 'Snicket, Lemony', expect: { match: ['S21'] } },
  { rule: 'AUT-2', q: 'bradbury ray', expect: { first: 'S16', match: ['S16'] } },
  { rule: 'AUT-2', q: 'covey sean', expect: { first: 'S19', match: ['S19'] } },
  { rule: 'AUT-3', q: 'rl stine', expect: { main: ['S4'], absent: ['S18', 'XS21'], reasons: [{ row: 'S4', includes: 'given names differ' }] }, note: "'rl' sits next to 'stine', an author word of S4, so it is optional there; for S18/XS21 it stays required and 'stine' is only fuzzy." },
  { rule: 'AUT-3', q: 'Stine, R.L.', expect: { first: 'S4', main: ['S4'] } },
  { rule: 'AUT-3', q: 'orwell, g.', expect: { first: 'S9', main: ['S9'] }, note: "'g' is George's first letter, so no 'given names differ' reason." },
  { rule: 'AUT-3', q: 'r.l. jokes', expect: { possible: ['S4', 'S6'], notMain: ['S4', 'S6'] }, note: "'jokes' is a title word, so the initials stay required; the prototype puts both in the main list." },
  { rule: 'AUT-3', q: 'tj haverstock', expect: { first: 'XS18', match: ['XS18'] }, note: "'T.J.' in the cell indexes the initials word 'tj'." },
  { rule: 'AUT-3', q: 'rj detectives', expect: { possible: ['XS18'], notMain: ['XS18'] } },
  { rule: 'AUT-4', q: 'cornelius pruitt', expect: { match: ['XS13'] }, note: 'Extra given names or suffixes in the cell never exclude a row.' },
  { rule: 'AUT-4', q: 'fairbrass jr', expect: { match: ['XS14'] } },
  { rule: 'AUT-4', q: 'mr fairbrass', expect: { match: ['XS14'] }, note: "'mr' is optional (the cell says Dr.)." },
  { rule: 'AUT-4', q: 'nandakumar editor', expect: { match: ['XS15'] }, note: 'Role words are optional; the prototype gives Possible.' },
  { rule: 'AUT-4', q: 'lotte brandvold (illustrator)', expect: { match: ['XS15'] } },
  { rule: 'AUT-5', q: 'lemarchant', expect: { main: ['XS10'] }, note: "Matches the joined pair 'le marchant' (Close)." },
  { rule: 'AUT-5', q: 'le marchant', expect: { match: ['XS10'] } },
  { rule: 'AUT-5', q: 'lestrange', expect: { match: ['XS11'] } },
  { rule: 'AUT-5', q: 'omara', expect: { match: ['XS12'] } },
  { rule: 'AUT-5', q: 'al', expect: { main: ['XS20'], absent: ['S10', 'S18'] }, note: "'al' is a searchable word (the prototype treats it as ignorable). Et Al is stripped from S10 and S18." },
  { rule: 'AUT-5', q: 'al rashidi', expect: { first: 'XS20', match: ['XS20'] } },
  { rule: 'AUT-6', q: 'daniel handler', expect: { main: ['S21'], reasons: [{ row: 'S21', includes: 'via alias' }] }, note: 'Needs the CONTRACT aliases. queries.js marks it unsolvable.' },
  { rule: 'AUT-6', q: 'daniel handler wide window', expect: { main: ['S21'], reasons: [{ row: 'S21', includes: 'via alias' }] }, note: 'Without the alias this is 2 of 4 words (Possible); the alias search gives Match and the best tier wins.' },
  { rule: 'AUT-6', q: 'handler', expect: { absent: ['S21'] }, note: 'Only a complete alias name widens the query.' },
  { rule: 'AUT-7', q: 'canfield et al', expect: { match: ['S10'] } },
  { rule: 'AUT-7', q: 'Jack Canfield Et Al', expect: { first: 'S10', match: ['S10'] } },
  { rule: 'AUT-7', q: 'canfield and hansen', expect: { possible: ['S10'], notMain: ['S10'] } },
  { rule: 'AUT-7', q: 'jack canfield and mark victor hansen', expect: { possible: ['S10'], notMain: ['S10'], reasons: [{ row: 'S10', includes: '1 of 2 authors' }] }, note: 'Two authors are named, so a row with one of them is Possible although only 2 of 5 words match.' },
  { rule: 'AUT-7', q: 'capecci & ziegler', expect: { possible: ['S18'], notMain: ['S18'] } },
  { rule: 'AUT-7', q: 'mark victor hansen', expect: { maxMain: 0, hint: 'etAl' }, needsSample: true, note: "The etAl hint needs an 'Et Al' row (S10)." },
  { rule: 'AUT-8', q: 'arora press', expect: { match: ['S5'] }, note: "The prototype gives Possible because it requires 'press'." },
  { rule: 'AUT-8', q: 'arora publishers', expect: { match: ['S5'] } },
  { rule: 'AUT-8', q: 'arora inc', expect: { match: ['S5'] } },
  { rule: 'AUT-8', q: 'arora book company', expect: { first: 'S5', match: ['S5'] } },
  { rule: 'AUT-9', q: 'kite', expect: { first: 'XS8', main: ['XS8', 'XS9'], before: [['XS8', 'XS9']] }, note: 'One-word query: the author hit ranks above the title hit; the prototype ranks the title first.' },
  { rule: 'AUT-9', q: 'green kite', expect: { first: 'XS9', match: ['XS9'], notMain: ['XS8'] } },
  { rule: 'AUT-9', q: 'wren', expect: { first: 'XC1', main: ['XC1', 'XA26', 'XS5', 'XR5', 'XT3'], before: [['XC1', 'XA26'], ['XR5', 'XT3']] }, note: "Resolved order: a whole-title-equal row ('The Wren') first, then author hits (Tobias Wren), then title-only hits (the prefix 'Wrenfield')." },
  { rule: 'AUT-10', q: 'orwell zebra crossing', expect: { possible: ['XS16'], reasons: [{ row: 'XS16', includes: 'author not listed' }] }, needsSample: true, note: "'N/A' counts as no author for the missing-author rule ('orwell' is an author word through S9)." },
  { rule: 'AUT-10', q: 'unknown', expect: { absent: ['XS17'] }, note: 'Placeholder authors are not indexed.' },
  { rule: 'AUT-10', q: 'tidewater hymnal unknown', expect: { close: ['XS17'], reasons: [{ row: 'XS17', includes: 'the whole listed title is in your search' }] }, note: "'unknown' can't match the placeholder (that would make it a Match); the reverse check makes it Close." },
  { rule: 'AUT-10', q: 'n/a', expect: { absent: ['XS16', 'S8', 'S17'] } },
  { rule: 'ALI-1', q: "philosopher's stone of brackenmoor", expect: { main: ['XS21'], reasons: [{ row: 'XS21', includes: 'via alias' }] } },
  { rule: 'ALI-1', q: "sorcerer's stone of brackenmoor", expect: { first: 'XS21', match: ['XS21'] }, note: 'A direct hit; the alias adds nothing.' },

  // =====================================================================================================
  // Titles: partial, longer, series, editions, look-alikes
  // =====================================================================================================
  { rule: 'titles.partial', q: '60 Seconds to Shine', expect: { state: 'ok', first: 'S18', match: ['S18'] } },
  { rule: 'titles.partial', q: 'one-minute monologues', expect: { match: ['S18'], notMain: ['S11'] } },
  { rule: 'titles.partial', q: 'sixty seconds to shi', expect: { match: ['S18'] } },
  { rule: 'titles.partial', q: 'sec shine', expect: { possible: ['S18'], notMain: ['S18'] }, note: "Only the last word prefix-matches; 'sec' is a finished word." },
  { rule: 'titles.partial', q: 'seconds sh', expect: { possible: ['S18'], notMain: ['S18'] }, note: "A 2-letter last word is not a prefix, and 'sh' is a required whole word." },
  { rule: 'titles.partial', q: 'monologues for men', expect: { possible: ['S18'], notMain: ['S18'] }, note: "No substring matching: 'men' does not match 'Women'." },
  { rule: 'titles.longer', q: 'Nineteen Eighty-Four by George Orwell (Penguin Modern Classics)', expect: { close: ['S9'], notMain: ['S8'], reasons: [{ row: 'S9', includes: 'the whole listed title is in your search' }] } },
  { rule: 'titles.longer', q: 'The 7 Habits of Highly Effective Teens: The Ultimate Teenage Success Guide', expect: { first: 'S19', close: ['S19'], notMain: ['S8', 'S12', 'S20'], reasons: [{ row: 'S19', includes: 'the whole listed title is in your search' }] } },
  { rule: 'titles.longer', q: '1984 study guide', expect: { first: 'S8', match: ['S8'], notMain: ['S9'] }, note: 'A one-word title counts as inside the query only with an author word in the query.' },
  { rule: 'titles.longer', q: 'skyfarer penguin', expect: { possible: ['XT4'], notMain: ['XT4'], reasons: [{ row: 'XT4', includes: 'matched 1 of 2 words' }] } },
  { rule: 'titles.longer', q: 'skyfarr sigrun halvorsen penguin', expect: { possible: ['XT4'], notMain: ['XT4'] }, note: 'The one-word title is matched only by fuzzy spelling, so the reverse check does not apply.' },
  { rule: 'titles.longer', q: '30 days the documentary by morgan spurlock', expect: { close: ['S14'], reasons: [{ row: 'S14', includes: 'the whole listed title is in your search' }] }, note: "The format word 'Disc' is not a meaningful title word." },
  { rule: 'titles.series-volume', q: 'The Wide Window (A Series of Unfortunate Events, #3)', expect: { first: 'S21', match: ['S21'] } },
  { rule: 'titles.series-volume', q: 'Unfortunate Events book three', expect: { match: ['S21'] } },
  { rule: 'titles.series-volume', q: 'wide window no. 3', expect: { match: ['S21'] } },
  { rule: 'titles.series-volume', q: 'wide window vol 3', expect: { match: ['S21'] } },
  { rule: 'titles.series-volume', q: '60 seconds to shine book 2', expect: { match: ['S18'] }, note: "S18 'Volume 2' shares the book key." },
  { rule: 'titles.series-volume', q: 'wide window book 4', expect: { possible: ['S21'], notMain: ['S21'] }, note: 'Same label, other number: Possible.' },
  { rule: 'titles.single-volume-note', q: 'A Series of Unfortunate Events', expect: { match: ['S21'], notes: [{ row: 'S21', includes: 'This listing names Book 3 only.' }] } },
  { rule: 'titles.single-volume-note', q: '60 seconds to shine', expect: { match: ['S18'], notes: [{ row: 'S18', includes: 'This listing names Volume 2 only.' }] } },
  { rule: 'titles.single-volume-note', q: '10-minute plays for teens', expect: { match: ['S11'], notes: [{ row: 'S11', includes: 'This listing names Volume 1 only.' }] }, note: "'Volume One' is written as a digit in the note." },
  { rule: 'titles.single-volume-note', q: 'lemony snicket', expect: { match: ['S21'], notes: [{ row: 'S21', includes: 'names Book 3 only' }] }, note: 'The note appears on author-only hits too.' },
  { rule: 'titles.whole-series', q: 'starfall rangers the ember gate', expect: { first: 'XT1', main: ['XT1', 'XT2'], notes: [{ row: 'XT1', includes: 'Covers a whole series' }] }, note: "XT1 is lifted by its series name and pinned above XT2, whose title equals the query." },
  { rule: 'titles.whole-series', q: 'the ember gate odile brancroft', expect: { first: 'XT1', main: ['XT1', 'XT2'] }, note: 'Lifted by the author match.' },
  { rule: 'titles.whole-series', q: 'the ember gate', expect: { match: ['XT2'], absent: ['XT1'] } },
  { rule: 'titles.whole-series', q: 'the frostwing wrenfield quartet', expect: { close: ['XT3'], notes: [{ row: 'XT3', includes: 'Covers a whole series' }] } },
  { rule: 'titles.whole-series', q: 'the obsidian lamplighter', expect: { state: 'ok', maxMain: 0, hint: 'seriesTip' }, note: 'No row contains either word.' },
  { rule: 'titles.whole-series', q: 'lemony snicket aarons hair', expect: { main: ['S22'], possible: ['S21'], notMain: ['S21'] }, note: "S21 ('Series of' + a single volume) is not a whole-series row, so its author match does not lift it." },
  { rule: 'titles.format-words', q: '30 Days DVD', expect: { first: 'S14', match: ['S14'] } },
  { rule: 'titles.format-words', q: '1984 paperback', expect: { match: ['S9', 'S8'], before: [['S9', 'S8']] }, note: 'Title equality ignores format words (the prototype shows S8 first).' },
  { rule: 'titles.format-words', q: 'farenheit 2nd edition', expect: { match: ['S16'], notMain: ['S10'] }, note: "The edition statement '2nd edition' is optional." },
  { rule: 'titles.format-words', q: 'dvd', expect: { match: ['S8'], notMain: ['S14', 'S17'] }, note: 'A lone format word becomes required and is matched in Title/Author/Memo only.' },
  { rule: 'titles.format-words', q: 'book', expect: { match: ['S5', 'S12', 'S21', 'O5', 'O6', 'O8'], notMain: ['S4', 'S6', 'S7', 'S9', 'S10', 'S11', 'S16', 'S18', 'S19', 'S20', 'S22', 'O7', 'XT2'] }, note: 'Type=Book cannot create a match, and pair terms (book1, book2) are not prefix targets.' },
  { rule: 'titles.format-words', q: 'the jungle book', expect: { absent: ['S5', 'S12', 'S21', 'O5', 'O6', 'O8', 'S9'] } },
  { rule: 'titles.paste-residue', q: '1984 study guide', expect: { first: 'S8', displayTitle: [{ row: 'S8', equals: '1984: A DVD Study Guide+3:15A13:153:173:193:401' }] } },
  { rule: 'titles.paste-residue', q: '13', expect: { match: ['S7'], absent: ['S8'] } },
  { rule: 'titles.paste-residue', q: '153', expect: { absent: ['S8'] } },
  { rule: 'titles.paste-residue', q: '401', expect: { absent: ['S8'] } },
  { rule: 'titles.paste-residue', q: 'study guide 401', expect: { notMain: ['S8'] }, note: 'A residue number never completes a match; S8 may be Possible.' },
  { rule: 'titles.pasted-listings', q: 'chicken soup paperback – march 3, 2015', expect: { match: ['S10'] }, note: 'The date is removed and paperback is optional (the prototype returns nothing).' },
  { rule: 'titles.pasted-listings', q: 'wide window 4.5 out of 5 stars', expect: { match: ['S21'] }, note: 'The rating is removed.' },
  { rule: 'titles.pasted-listings', q: 'Seven Habits of Highly Effective Teens Sean Covey (Author) Paperback – December 1, 1998', expect: { first: 'S19', match: ['S19'] } },
  { rule: 'titles.pasted-listings', q: 'is 1984 allowed', expect: { match: ['S9', 'S8'], before: [['S9', 'S8']] }, note: 'Question words are optional (the prototype drops S8).' },
  { rule: 'titles.pasted-listings', q: 'Orwell, G. (1949). Nineteen eighty-four. Secker & Warburg.', expect: { close: ['S9'], notMain: ['S8'] }, note: '(1949) is removed; the reverse check covers the publisher words.' },
  { rule: 'titles.pasted-listings', q: '2001 user guide', expect: { match: ['S12'] }, note: 'A bare 4-digit title number is not a date.' },
  { rule: 'titles.pasted-urls', q: 'https://www.amazon.com/Fahrenheit-451-Ray-Bradbury/dp/1451673310', expect: { close: ['S16'] }, note: 'Later rule; this passes through the ordinary reverse check on the URL slug.' },
  { rule: 'titles.regional', q: "quentin ashby and the sorcerer's lantern", expect: { possible: ['XT8'], notMain: ['XT8'], reasons: [{ row: 'XT8', includes: 'matched 3 of 4 words' }] } },
  { rule: 'titles.look-alikes', q: '1984', expect: { first: 'S9', match: ['S9', 'S8'], before: [['S9', 'S8']] } },
  { rule: 'titles.look-alikes', q: 'the 7 habits of highly effective people', expect: { possible: ['S19'], notMain: ['S19'], reasons: [{ row: 'S19', includes: 'matched 4 of 5 words' }] } },
  { rule: 'titles.look-alikes', q: '7 habits', expect: { first: 'S19', match: ['S19'], notMain: ['S20'] } },
  { rule: 'titles.look-alikes', q: 'chicken soup for the teenage soul', expect: { possible: ['S10'], notMain: ['S10'], reasons: [{ row: 'S10', includes: 'matched 2 of 4 words' }] }, note: "'N of R' counts anchored words only: soul~Soup (fuzzy) is not counted." },
  { rule: 'titles.same-work-groups', q: 'velvet quarry', expect: { first: 'XT6', match: ['XT5', 'XT6', 'XT7'], before: [['XT6', 'XT5']] }, note: 'The Ministry row XT6 leads its group.' },
  { rule: 'titles.same-work-groups', q: 'velvet quarry kes', expect: { first: 'XT6', match: ['XT5'], close: ['XT6', 'XT7'], before: [['XT6', 'XT5']] }, note: 'XT5 is a full match through Banned By KES; XT6/XT7 are Close by the reverse check and keep their tier inside the group.' },
  { rule: 'titles.same-work-groups', q: 'quarry kes', expect: { first: 'XT6', main: ['XT5', 'XT6', 'XT7'], before: [['XT6', 'XT5']] }, note: 'Never buried: XT6/XT7 would be Possible (1 of 2) and are pulled into main beside XT5.' },
  { rule: 'titles.same-work-groups', q: 'kallas', expect: { first: 'XT6', match: ['XT5', 'XT6', 'XT7'] }, note: "'Kallas, Imre' and 'Imre Kallas' share an author key." },

  // =====================================================================================================
  // ISBNs
  // =====================================================================================================
  { rule: 'isbn.formats', q: '979-8-89180-854-6', expect: { state: 'ok', first: 'O5', match: ['O5'], maxMain: 1 } },
  { rule: 'isbn.formats', q: 'ISBN: 9798891808546', expect: { match: ['O5'], maxMain: 1 } },
  { rule: 'isbn.formats', q: 'isbn-13 979 8891 808546', expect: { match: ['O5'] } },
  { rule: 'isbn.formats', q: '0-306-40615-2', expect: { match: ['XT9'] }, note: "The cell '306406152' lost its leading 0." },
  { rule: 'isbn.formats', q: '97988912', expect: { absent: ['XT12'], hint: 'isbnNoMatch' }, note: 'The scientific-notation cell is not indexed (the prototype indexes it as 97988912).' },
  { rule: 'isbn.formats', q: '751459', expect: { match: ['S21'] }, note: 'A 6-digit ISBN-shaped query is also searched as one whole word in Title/Author/Memo.' },
  { rule: 'isbn.check-digits', q: '81-7450-835-X', expect: { match: ['O4'] } },
  { rule: 'isbn.check-digits', q: '978-81-7450-835-5', expect: { match: ['O4'] } },
  { rule: 'isbn.check-digits', q: '8174508350', expect: { match: ['O4'] }, note: 'Wrong check digit ignored.' },
  { rule: 'isbn.check-digits', q: '979-8-89180-854-0', expect: { match: ['O5'] }, note: 'Wrong ISBN-13 check digit ignored (the prototype returns nothing).' },
  { rule: 'isbn.check-digits', q: '9788174508365', expect: { absent: ['O4'], hint: 'isbnNoMatch' }, note: 'A core digit differs: a different book.' },
  { rule: 'isbn.prefix-while-typing', q: '979', expect: { absent: ['O5', 'O6', 'O7', 'O8', 'XT12'] } },
  { rule: 'isbn.prefix-while-typing', q: '979889', expect: { isbnPrefix: ['O5', 'O6', 'O7', 'O8'], absent: ['XT12'], maxMain: 0 } },
  { rule: 'isbn.prefix-while-typing', q: '979-8-89180-8', expect: { isbnPrefix: ['O5', 'O6', 'O8'], absent: ['O7'] }, note: '10 digits that are not an exact ISBN-10 hit fall back to the prefix group.' },
  { rule: 'isbn.prefix-while-typing', q: '979889180854', expect: { isbnPrefix: ['O5'], notMain: ['O5'] } },
  { rule: 'isbn.prefix-while-typing', q: '030640', expect: { isbnPrefix: ['XT9'] }, note: 'Prefix of the 10-digit form.' },
  { rule: 'isbn.prefix-while-typing', q: '978-0-306', expect: { isbnPrefix: ['XT9'] }, note: 'Hyphenated partial, prefix of the 13-digit form (the prototype returns nothing).' },
  { rule: 'isbn.in-longer-query', q: 'Fahrenheit 451 ISBN 978-1-4516-7331-9', expect: { main: ['S16'] } },
  { rule: 'isbn.in-longer-query', q: 'the wide window 0306406152', expect: { match: ['S21', 'XT9'] }, note: 'The ISBN is optional for S21; its exact hit also puts XT9 in main.' },
  { rule: 'isbn.in-longer-query', q: 'little blue envelopes 13 2008 2009', expect: { main: ['S7'], absent: ['XT13'] } },
  { rule: 'isbn.in-longer-query', q: 'ISBN 978 0 306 40615 7', expect: { match: ['XT9'] } },
  { rule: 'isbn.in-longer-query', q: 'Amplify Core Knowledge Unit 4 Don Quixote 979-8-89180-854-6', expect: { first: 'O5', match: ['O5'] }, note: "An exact ISBN hit is a Match even though 'core'/'knowledge' miss." },
  { rule: 'isbn.in-longer-query', q: 'don quixote 979889180', expect: { match: ['O5'] }, note: 'A partial ISBN (9+ digits) in a mixed query is optional.' },
  { rule: 'isbn.multi-and-placeholders', q: '9781234567897', expect: { match: ['XT10'] } },
  { rule: 'isbn.multi-and-placeholders', q: '0-9752298-0-X', expect: { match: ['XT10'] }, note: 'The second ISBN in the cell.' },
  { rule: 'isbn.multi-and-placeholders', q: '9780975229804', expect: { match: ['XT10'] } },
  { rule: 'isbn.multi-and-placeholders', q: '978123', expect: { isbnPrefix: ['XT10'] } },
  { rule: 'isbn.multi-and-placeholders', q: 'not available', expect: { absent: ['XT11'] }, note: 'Placeholder text in an ISBN cell is not word-indexed.' },
  { rule: 'isbn.no-match-hint', q: '9780140449136', expect: { state: 'ok', maxMain: 0, hint: 'isbnNoMatch' } },
  { rule: 'isbn.no-match-hint', q: '0-14-044913-2', expect: { hint: 'isbnNoMatch' } },
  { rule: 'isbn.no-match-hint', q: 'ISBN 978-0-14-044913-6', expect: { hint: 'isbnNoMatch' } },
  { rule: 'isbn.no-match-hint', q: 'the obsidian lamplighter 9780140449136', expect: { maxMain: 0, hint: 'isbnNoMatch' }, note: 'Mixed query where nothing matches.' },

  // =====================================================================================================
  // Search behaviour and results (BEH)
  // =====================================================================================================
  { rule: 'BEH-NORMALIZE', q: 'the seventh knot', expect: { first: 'S20', match: ['S20'], reasons: [{ row: 'S20', includes: 'seventh = 7th' }] } },
  { rule: 'BEH-NORMALIZE', q: '7th Knot, The', expect: { first: 'S20', match: ['S20'] } },
  { rule: 'BEH-TIER-MATCH', q: 'the 7th knot', expect: { state: 'ok', first: 'S20', match: ['S20'] } },
  { rule: 'BEH-TIER-MATCH', q: 'orw', expect: { match: ['S9'] }, note: 'A last-word prefix from 3 letters is Match, not Close.' },
  { rule: 'BEH-TIER-MATCH', q: 'lemony sni', expect: { first: 'S21', match: ['S21'] } },
  { rule: 'BEH-TIER-MATCH', q: '101', expect: { match: ['S4', 'S5', 'S6'] } },
  { rule: 'BEH-TIER-CLOSE', q: 'fahrenheit 451', expect: { close: ['S16'], reasons: [{ row: 'S16', includes: 'similar spelling: Farenheit' }] } },
  { rule: 'BEH-TIER-CLOSE', q: 'melvin berger', expect: { close: ['S6'], reasons: [{ row: 'S6', includes: 'similar spelling: Melvn' }] } },
  { rule: 'BEH-TIER-CLOSE', q: 'kathleen karl', expect: { close: ['S20'], reasons: [{ row: 'S20', includes: 'similar spelling: Karr' }] }, note: 'Any fuzzy hit is Close; the prototype demoted 1-edit hits on short words to Possible.' },
  { rule: 'BEH-TIER-CLOSE', q: 'bradberry', expect: { close: ['S16'], reasons: [{ row: 'S16', includes: 'similar spelling: Bradbury' }] }, note: '2 edits on 8+ letters is Close; the prototype put fuzzy2 in Possible.' },
  { rule: 'BEH-TIER-CLOSE', q: 'grandmother stories', expect: { close: ['S5'], reasons: [{ row: 'S5', includes: 'Grand Mother' }] } },
  { rule: 'BEH-TIER-CLOSE', q: 'fairytales', expect: { close: ['S15'], reasons: [{ row: 'S15', includes: 'Fairy Tales' }] } },
  { rule: 'BEH-REVERSE', q: 'The 7 Habits of Highly Effective Teens: The Ultimate Teenage Success Guide', expect: { close: ['S19'], reasons: [{ row: 'S19', includes: 'the whole listed title is in your search' }] } },
  { rule: 'BEH-REVERSE', q: 'Nineteen Eighty-Four by George Orwell (Penguin Modern Classics)', expect: { close: ['S9'], reasons: [{ row: 'S9', includes: 'the whole listed title is in your search' }] } },
  { rule: 'BEH-REVERSE', q: '1984 study guide', expect: { first: 'S8', match: ['S8'], absent: ['S9'] }, note: 'The one-word title 1984 needs an author word in the query.' },
  { rule: 'BEH-REVERSE', q: '1984 dvd study guide', expect: { match: ['S8'], absent: ['S9'] }, note: 'queries.js lists S9 as ok; the PRD excludes it.' },
  { rule: 'BEH-REVERSE', q: '1984 penguin modern classics', expect: { absent: ['S9'] } },
  { rule: 'BEH-REVERSE', q: 'quillons lantern hubs', expect: { close: ['XR5'], reasons: [{ row: 'XR5', includes: 'the whole listed title is in your search' }] } },
  { rule: 'BEH-TIER-POSSIBLE', q: 'kids jokes', expect: { possible: ['S4', 'S6'], notMain: ['S4', 'S6'], reasons: [{ row: 'S4', includes: 'matched 1 of 2 words' }] } },
  { rule: 'BEH-TIER-POSSIBLE', q: 'stine', expect: { match: ['S4'], possible: ['S18'], reasons: [{ row: 'S18', includes: 'similar spelling: Shine' }] } },
  { rule: 'BEH-TIER-POSSIBLE', q: 'shine', expect: { match: ['S18'], possible: ['S4'], reasons: [{ row: 'S4', includes: 'similar spelling: Stine' }] } },
  { rule: 'BEH-TIER-POSSIBLE', q: 'munch snowflakes', expect: { absent: ['S22'] }, note: 'A fuzzy hit never anchors a Possible.' },
  { rule: 'BEH-TIER-POSSIBLE', q: 'textbook xylophonic', expect: { absent: ['O7'] }, note: 'A Type hit never anchors a Possible.' },
  { rule: 'BEH-TIER-POSSIBLE', q: 'stephen covey', expect: { possible: ['S19'], notMain: ['S19'], reasons: [{ row: 'S19', includes: 'matched 1 of 2 words' }] } },
  { rule: 'BEH-POSSIBLE-NOAUTHOR', q: 'orwell 1984', expect: { match: ['S9'], possible: ['S8'], reasons: [{ row: 'S8', includes: 'author not listed' }] } },
  { rule: 'BEH-POSSIBLE-NOAUTHOR', q: '1984 by george orwell', expect: { match: ['S9'], possible: ['S8'], reasons: [{ row: 'S8', includes: 'author not listed' }] }, note: 'The prototype misses S8 (1 of 3 words).' },
  { rule: 'BEH-POSSIBLE-NOAUTHOR', q: 'bradbury fairy tales', expect: { possible: ['S15'], absent: ['S16'], reasons: [{ row: 'S15', includes: 'author not listed' }] } },
  { rule: 'BEH-POSSIBLE-NOAUTHOR', q: 'orwell', expect: { match: ['S9'], absent: ['S8'] } },
  { rule: 'BEH-POSSIBLE-NOAUTHOR', q: 'marisol venn', expect: { absent: ['XR4'] }, note: 'The authorless XR4 misses only author words but has no anchor.' },
  { rule: 'BEH-SECTIONS', q: 'orwell 1984', expect: { main: ['S9'], possible: ['S8'], notMain: ['S8'] } },
  { rule: 'BEH-SECTIONS', q: 'quillons lantern hubs', expect: { first: 'XR3', main: ['XR2', 'XR3', 'XR5'], match: ['XR2'], possible: ['XR4'], notMain: ['XR4'], before: [['XR3', 'XR2'], ['XR2', 'XR5'], ['XR3', 'XR5']] }, note: 'The group (XR3 Ministry on top, XR2) sits at XR2 (Match) before the Close hit XR5.' },
  { rule: 'BEH-RANK', q: 'marzipan lighthouse', expect: { first: 'XR7', match: ['XR7', 'XR8', 'XR9'], before: [['XR7', 'XR9'], ['XR9', 'XR8']] }, note: 'Whole title first, then the in-order phrase; the prototype ties XR8/XR9.' },
  { rule: 'BEH-RANK', q: 'lighthouse marzipan', expect: { first: 'XR7', before: [['XR7', 'XR8'], ['XR8', 'XR9']] }, note: 'Whole-title equality ignores word order; XR8 has the typed order.' },
  { rule: 'BEH-RANK', q: 'juniper', expect: { main: ['XR10', 'XR11'], before: [['XR10', 'XR11']] }, note: 'One-word query: the author hit leads; the prototype ranks the title hit first.' },
  { rule: 'BEH-RANK', q: 'copper kettle dvd', expect: { main: ['XR12', 'XR13'], before: [['XR13', 'XR12']] }, note: 'The optional format word matched (Type DVD) raises rank.' },
  { rule: 'BEH-RANK', q: 'copper kettle ballads dvd', expect: { first: 'XR12', before: [['XR12', 'XR13']] }, note: "Format words don't break whole-title equality; the prototype ranks XR13 first." },
  { rule: 'BEH-GROUP', q: 'quillons lantern', expect: { main: ['XR2', 'XR3', 'XR4', 'XR5'], before: [['XR3', 'XR2'], ['XR2', 'XR4'], ['XR5', 'XR4']] } },
  { rule: 'BEH-GROUP', q: 'marisol venn', expect: { main: ['XR2', 'XR3'], before: [['XR3', 'XR2']], absent: ['XR5'] } },
  { rule: 'BEH-GROUP', q: 'marisol venn hubs', expect: { main: ['XR2', 'XR3'], before: [['XR3', 'XR2']], reasons: [{ row: 'XR3', includes: 'same title and author' }] }, note: 'XR3 is Possible on its own (2 of 3); the group pulls it into main as Close, Ministry on top.' },
  { rule: 'BEH-GROUP', q: 'aaron', expect: { main: ['S22', 'S23'], before: [['S22', 'S23']] }, note: 'Never ranked by severity: the Ministry row S23 stays below S22 (different works).' },
  { rule: 'BEH-LOOKALIKE', q: '1984', expect: { first: 'S9', main: ['S8', 'S9'], before: [['S9', 'S8']] } },
  { rule: 'BEH-LOOKALIKE', q: 'guide', expect: { main: ['S8', 'S12'] } },
  { rule: 'BEH-DISPLAY-TITLE', q: 'the seventh knot', expect: { displayTitle: [{ row: 'S20', equals: 'The 7th Knot' }] } },
  { rule: 'BEH-DISPLAY-TITLE', q: 'second helping chicken soup', expect: { match: ['S10'], displayTitle: [{ row: 'S10', equals: 'A 2nd Helping of Chicken Soup' }] } },
  { rule: 'BEH-DISPLAY-TITLE', q: 'seven habits', expect: { displayTitle: [{ row: 'S19', equals: 'The 7 Habits of Highly Effective Teens' }] } },
  { rule: 'BEH-DISPLAY-TITLE', q: 'marisol venn', expect: { displayTitle: [{ row: 'XR3', equals: "The Quillon's Lantern" }, { row: 'XR2', equals: "Quillon's Lantern" }] } },
  { rule: 'BEH-DISPLAY-TITLE', q: 'don quixote', expect: { match: ['O5'] }, note: "O5's display title is the cell with its trailing space trimmed and its en dashes kept (checked on synthetic XN17 under PUNC-7)." },
  { rule: 'BEH-DISPLAY-TITLE', q: 'wide window', expect: { displayTitle: [{ row: 'S21', equals: 'A Series of Unfortunate Events - The Wide Window -Book 3' }] } },
  { rule: 'BEH-REASONS', q: 'thirteen little blue envelopes', expect: { match: ['S7'], reasons: [{ row: 'S7', includes: 'thirteen = 13' }] } },
  { rule: 'BEH-REASONS', q: 'grandmother', expect: { close: ['S5'], reasons: [{ row: 'S5', includes: 'written as two words: Grand Mother' }] } },
  { rule: 'BEH-REASONS', q: 'supplementary', expect: { close: ['O4'], reasons: [{ row: 'O4', includes: 'similar spelling: Supplementay' }] }, note: "Type 'Supplementary' matches exactly but only completes; the title evidence is fuzzy, so Close." },
  { rule: 'BEH-REASONS', q: 'morgan spurlock', expect: { close: ['S14'], reasons: [{ row: 'S14', includes: 'similar spelling: Suprlock' }] } },
  { rule: 'BEH-HIGHLIGHT', q: 'the seventh knot', expect: { displayTitle: [{ row: 'S20', equals: 'The 7th Knot' }], reasons: [{ row: 'S20', includes: 'seventh = 7th' }] }, note: 'Unit-test highlights.title == [[0,3],[4,7],[8,12]].' },
  { rule: 'BEH-HIGHLIGHT', q: '1984 study guide', expect: { match: ['S8'] }, note: 'Unit-test highlights.title on S8 == [[0,4],[12,17],[18,23]], nothing inside the residue.' },
  { rule: 'BEH-VOLUME', q: 'amplify', expect: { main: ['O5', 'O6', 'O7', 'O8'] }, note: 'The engine never truncates.' },

  // =====================================================================================================
  // Sheet structure seen by the engine (SHEET)
  // =====================================================================================================
  { rule: 'SHEET-NOTES', q: 'library', expect: { absent: ['S5'] } },
  { rule: 'SHEET-NOTES', q: 'classroom highlighted', expect: { absent: ['S5'] } },
  { rule: 'SHEET-NOTES', q: 'red', expect: { absent: ['S5'] } },
  { rule: 'SHEET-NOTES', q: 'blue', expect: { main: ['S7'], absent: ['S5'] } },
  { rule: 'SHEET-FLOOD', q: 'ministry', expect: { state: 'ok', maxMain: 0, absent: ['S8', 'S9', 'S11', 'S12', 'S14', 'S16', 'S17', 'S18', 'S21', 'S23', 'O4', 'O5', 'O6', 'O7', 'O8', 'XR3', 'XR4', 'XR6'] }, note: 'The prototype returns 15 strong rows (queries.js ok MIN).' },
  { rule: 'SHEET-FLOOD', q: 'kes', expect: { absent: ['S4', 'S5', 'S6', 'XR5'] } },
  { rule: 'SHEET-FLOOD', q: 'book', expect: { main: ['S12', 'S21', 'O5', 'O6', 'O8'], absent: ['S4', 'S6', 'S7', 'S9', 'S10', 'S13', 'S15', 'S16', 'S18', 'S19', 'S20', 'S22', 'O7', 'XR2', 'XR3', 'XR7', 'XR10'] } },
  { rule: 'SHEET-FLOOD', q: '2009', expect: { absent: ['S6', 'S7', 'S8', 'S10', 'S13', 'S14', 'S17', 'S19', 'S20', 'S22'] } },
  { rule: 'SHEET-FLOOD', q: '2010', expect: { absent: ['S4', 'S6', 'S11', 'S20', 'S22'] }, note: 'Digit-only words are never joined.' },
  { rule: 'SHEET-FLOOD', q: 'textbook', expect: { absent: ['O7', 'O8'] }, note: 'Type only; the prototype also hit O7/O8 through the fuzzy-prefix bug.' },
  { rule: 'SHEET-FLOOD-COMPLETE', q: 'orwell book', expect: { first: 'S9', match: ['S9'], absent: ['S8', 'S12', 'S21'] } },
  { rule: 'SHEET-FLOOD-COMPLETE', q: 'renaissance textbook', expect: { first: 'O7', match: ['O7'], possible: ['O8'] }, note: 'Type Textbook completes the match.' },
  { rule: 'SHEET-FLOOD-COMPLETE', q: 'ministry dvd', expect: { main: ['S8'], absent: ['S9', 'S11', 'S12', 'S14', 'S16', 'S17', 'S18', 'S21', 'S23', 'O4', 'O5', 'O6', 'O7', 'O8', 'XR3', 'XR4', 'XR5', 'XR6'] } },
  { rule: 'SHEET-FLOOD-COMPLETE', q: 'ministry book', expect: { main: ['S12', 'S21', 'O5', 'O6', 'O8'], absent: ['S8', 'S9', 'S11', 'S14', 'S16', 'S17', 'S18', 'S23', 'O4', 'O7', 'XR3', 'XR4', 'XR6'] } },
  { rule: 'SHEET-FLOOD-COMPLETE', q: 'dvd', expect: { main: ['S8'], absent: ['XR5', 'XR13'] } },
  { rule: 'SHEET-FLOOD-COMPLETE', q: 'hubs', expect: { absent: ['S6', 'S22', 'XR2'] } },
  { rule: 'SHEET-NUMBER-TITLE', q: '1984', expect: { first: 'S9', displayTitle: [{ row: 'S9', equals: '1984' }] } },
  { rule: 'SHEET-NUMBER-TITLE', q: 'orwell', expect: { main: ['S9'], displayTitle: [{ row: 'S9', equals: '1984' }] } },
  { rule: 'SHEET-JUNK', q: '1984 study guide', expect: { match: ['S8'], displayTitle: [{ row: 'S8', equals: '1984: A DVD Study Guide+3:15A13:153:173:193:401' }] } },
  { rule: 'SHEET-JUNK', q: '13', expect: { main: ['S7'], absent: ['S8'] } },
  { rule: 'SHEET-JUNK', q: '153', expect: { absent: ['S8'] } },
  { rule: 'SHEET-JUNK', q: 'zephyrine almanac', expect: { first: 'XR1', match: ['XR1'], displayTitle: [{ row: 'XR1', equals: 'Zephyrine Almanac+4:22B9:310:311' }] } },
  { rule: 'SHEET-JUNK', q: '310', expect: { absent: ['XR1'] } },

  // =====================================================================================================
  // Deliberately not solved (DNS)
  // =====================================================================================================
  { rule: 'DNS-TRANSLATION', q: 'مزرعة الحيوان', expect: { first: 'XR6', match: ['XR6'] } },
  { rule: 'DNS-TRANSLATION', q: 'animal farm', expect: { absent: ['XR6'] } },
  { rule: 'DNS-TRANSLATION', q: 'orwell', expect: { main: ['S9'], absent: ['XR6'] } },
  { rule: 'DNS-FACTS', q: 'mark victor hansen', expect: { maxMain: 0, absent: ['S10'], hint: 'etAl' } },
  { rule: 'DNS-FACTS', q: 'the ersatz elevator', expect: { absent: ['S21'] } },
  { rule: 'DNS-FACTS', q: '9780451524935', expect: { maxMain: 0, hint: 'isbnNoMatch' } },
  { rule: 'DNS-FACTS', q: 'series of unfortunate events', expect: { match: ['S21'], notes: [{ row: 'S21', includes: 'Book 3 only' }] } },
  { rule: 'DNS-OTHER-WORKS', q: 'animal farm orwell', expect: { maxMain: 0, absent: ['S8', 'S9', 'XR6'], hint: 'authorHasOthers' } },
  { rule: 'DNS-OTHER-WORKS', q: 'stephen covey', expect: { possible: ['S19'], notMain: ['S19'], hint: 'authorHasOthers' } },
  { rule: 'DNS-OTHER-WORKS', q: 'lemony snicket the ersatz elevator', expect: { possible: ['S21'], notMain: ['S21'], hint: 'authorHasOthers' } },
  { rule: 'DNS-FIX-ERRORS', q: 'fahrenheit 451', expect: { displayTitle: [{ row: 'S16', equals: '451 Farenheit' }] } },
  { rule: 'DNS-FIX-ERRORS', q: 'supplementary english class 8', expect: { close: ['O4'], reasons: [{ row: 'O4', includes: 'similar spelling: Supplementay' }] }, note: 'The reason names the sheet spelling; display.title keeps the cell as written.' },
  { rule: 'DNS-STEMMING', q: 'humor', expect: { absent: ['S4', 'S6'] } },
  { rule: 'DNS-STEMMING', q: 'joking', expect: { absent: ['S4', 'S6'] } },
  { rule: 'DNS-STEMMING', q: 'teenagers', expect: { absent: ['S11', 'S19'] } },
  { rule: 'DNS-STEMMING', q: 'kids jokes', expect: { notMain: ['S4', 'S6'] } },
  { rule: 'DNS-MERGE', q: 'quillons lantern', expect: { main: ['XR2', 'XR3', 'XR5'] } },
  { rule: 'DNS-MERGE', q: 'venn marisol', expect: { main: ['XR2', 'XR3'], before: [['XR3', 'XR2']] } },
];

// Changes to prototype/queries.js where the PRD changes behaviour (see the regression semantics at the top of this file).
const queryOverrides = {
  'the alchemist': { exp: ['XA1'], note: "Synthetic XA1 'Alchemist, The: A Fable…' is listed (article before a subtitle)." },
  al: { exp: ['XS20'], note: "'al' is an ordinary 2-letter word, not ignorable: synthetic XS20 'Nadia Al Rashidi' must be found. Et Al stays stripped, so S10/S18 stay out." },
  'daniel handler': { exp: ['S21'], note: 'Solved by the alias list (pen name -> Lemony Snicket), labelled via alias.' },
  'core knowledge language arts unit 4': { exp: ['O5'], ok: ['O6', 'O7', 'O8'], note: 'Solved by the alias list (acronym CKLA), labelled via alias.' },
  'mark victor hansen': { exp: [], note: 'Still not findable (a co-author hidden behind Et Al); now scored as a no-answer query with hint etAl.' },
  '7': { ok: ['O6'], note: "O6 'Unit 7' is a legitimate whole-word match for 7." },
  kes: { ok: [], note: 'Banned By never creates a match: nothing is returned (the prototype returned S5 via Type/Banned By).' },
  ministry: { ok: [], note: 'Banned By never creates a match: nothing is returned (the prototype returned 15 rows).' },
  fa: { ok: [], note: 'No prefix below 3 letters: nothing is returned, with hint keepTyping (the prototype returned S15, S16).' },
  so: { ok: ['O4'], note: "Whole word only: O4 'It So Happened' (the prototype also returned S10 'Soup' by 2-letter prefix)." },
  '1984 dvd study guide': { ok: [], note: "A one-word title ('1984') is inside a query only with one of its author words: S9 is not returned." },
  'animal farm orwell': { ok: [], note: 'Nothing is returned (S9 matches 1 of 3 words; S8 has no anchor); hint authorHasOthers.' },
  'The 7 Habits of Highly Effective People': { ok: ['S19'], note: 'S19 is Possible (4 of 5 words); S20 (1 of 5) is no longer returned.' },
  'thirteen reasons why': { ok: [], note: 'S7 matches 1 of 3 words and is not returned.' },
  '8th class': { ok: ['O5', 'O6', 'O7', 'O8'], note: "O5–O8 'Grade 5' are the same label (grade) with another number: Possible, per the label-pair rule (the prototype listed only O7, O8)." },
};

module.exports = { syntheticRows, cases, queryOverrides, aliases };
