// Adversarial teacher queries. Row ids: S<n> = Sheet1!<n>, O<n> = 'Other Materials'!<n>.
// exp  = rows that MUST come back (recall is measured on these)
// ok   = rows that may come back without counting as noise (same author, same series, etc.)
// uns  = true when no reasonable rule can match (pen names, acronyms, other works): reported, not in recall
// enter= true when the query is submitted with Enter (1-char queries)
'use strict';
const MIN = ['S8','S9','S11','S12','S14','S16','S17','S18','S21','S23','O4','O5','O6','O7','O8'];
const CKLA = ['O5','O6','O7','O8'];
const Q = [
  // ---------- Articles ----------
  { q: 'The 7th Knot', exp: ['S20'], cat: 'Articles' },
  { q: 'the seventh knot', exp: ['S20'], cat: 'Articles' },
  { q: '7th Knot, The', exp: ['S20'], cat: 'Articles' },
  { q: 'A 2nd Helping of Chicken Soup', exp: ['S10'], cat: 'Articles' },
  { q: 'a second helping of chicken soup', exp: ['S10'], cat: 'Articles' },
  { q: 'second helping chicken soup', exp: ['S10'], cat: 'Articles' },
  { q: 'The 7 Habits of Highly Effective Teens', exp: ['S19'], ok: ['S20'], cat: 'Articles' },
  { q: 'seven habits', exp: ['S19'], ok: ['S20'], cat: 'Numbers' },
  { q: '7 Habits of Highly Effective Teens, The', exp: ['S19'], ok: ['S20'], cat: 'Articles' },
  { q: 'Series of Unfortunate Events, A', exp: ['S21'], cat: 'Articles' },
  { q: 'the wide window', exp: ['S21'], cat: 'Articles' },
  { q: 'wide window', exp: ['S21'], cat: 'Articles' },
  { q: 'the alchemist', exp: [], cat: 'Articles (not listed)' },
  { q: 'the', exp: [], cat: 'Stopword-only' },
  { q: 'a', exp: [], cat: 'Stopword-only' },
  { q: 'of the', exp: [], cat: 'Stopword-only' },
  // ---------- Authors ----------
  { q: 'stine', exp: ['S4'], cat: 'Authors' },
  { q: 'rl stine', exp: ['S4'], cat: 'Authors/initials' },
  { q: 'r.l. stine', exp: ['S4'], cat: 'Authors/initials' },
  { q: 'R. L. Stine', exp: ['S4'], cat: 'Authors/initials' },
  { q: 'Stine, R.L.', exp: ['S4'], cat: 'Authors/initials' },
  { q: 'bob stine', exp: ['S4'], cat: 'Authors' },
  { q: 'spurlock', exp: ['S14'], cat: 'Typos in sheet' },
  { q: 'morgan spurlock', exp: ['S14'], cat: 'Typos in sheet' },
  { q: 'Spurlock, Morgan', exp: ['S14'], cat: 'Typos in sheet' },
  { q: 'melvin berger', exp: ['S6'], cat: 'Typos in sheet' },
  { q: 'berger', exp: ['S6'], cat: 'Authors' },
  { q: 'orwell', exp: ['S9'], ok: ['S8'], cat: 'Authors' },
  { q: 'Orwell, George', exp: ['S9'], ok: ['S8'], cat: 'Authors' },
  { q: 'orwel', exp: ['S9'], ok: ['S8'], cat: 'Typos in query' },
  { q: 'bradbury', exp: ['S16'], cat: 'Authors' },
  { q: 'Bradbury, Ray', exp: ['S16'], cat: 'Authors' },
  { q: 'bradbery', exp: ['S16'], cat: 'Typos in query' },
  { q: 'lemony snicket', exp: ['S21'], cat: 'Authors' },
  { q: 'Snicket, Lemony', exp: ['S21'], cat: 'Authors' },
  { q: 'snicker', exp: ['S21'], cat: 'Typos in query (autocorrect)' },
  { q: 'jack canfield', exp: ['S10'], cat: 'Authors' },
  { q: 'canfield and hansen', exp: ['S10'], cat: 'Authors/co-author' },
  { q: 'capecci & ziegler', exp: ['S18'], cat: 'Authors/co-author' },
  { q: 'Kristen Dabrowski', exp: ['S11'], cat: 'Authors' },
  { q: 'Dąbrowski', exp: ['S11'], cat: 'Accents' },
  { q: 'dabrowsky', exp: ['S11'], cat: 'Typos in query' },
  { q: 'munch', exp: ['S22'], cat: 'Typos in query (autocorrect)' },
  { q: 'sean covey', exp: ['S19'], cat: 'Authors' },
  { q: 'karr', exp: ['S20'], cat: 'Authors' },
  { q: 'maureen johnson', exp: ['S7'], cat: 'Authors' },
  { q: 'arora', exp: ['S5'], cat: 'Authors/publisher' },
  { q: 'daniel handler', exp: ['S21'], uns: true, cat: 'Pen name (unsolvable)' },
  { q: 'mark victor hansen', exp: ['S10'], uns: true, cat: 'Unlisted co-author (unsolvable)' },
  { q: 'stephen covey', exp: [], ok: ['S19'], cat: 'Same surname, other author' },
  { q: 'goosebumps rl stine', exp: [], ok: ['S4'], cat: 'Other work by listed author' },
  { q: 'animal farm orwell', exp: [], ok: ['S9', 'S8'], cat: 'Other work by listed author' },
  // ---------- Titles / numbers ----------
  { q: 'fahrenheit 451', exp: ['S16'], cat: 'Typos in sheet + order' },
  { q: 'FAHRENHEIT 451', exp: ['S16'], cat: 'Case' },
  { q: 'Fahrenheit 451: A Novel (60th Anniversary Edition)', exp: ['S16'], cat: 'Subtitle/edition appended' },
  { q: 'Fahrenheit 451 by Ray Bradbury Paperback – January 10, 2012', exp: ['S16'], cat: 'Pasted listing' },
  { q: 'Fahrenheit 451 Ray Bradbury 9781451673319', exp: ['S16'], cat: 'Pasted listing with ISBN' },
  { q: 'farenheit', exp: ['S16'], cat: 'Titles' },
  { q: 'fahren', exp: ['S16'], cat: 'Typing (prefix)' },
  { q: 'fahrenheit four fifty one', exp: ['S16'], cat: 'Numbers (spoken)' },
  { q: '451', exp: ['S16'], cat: 'Numbers' },
  { q: '1984', exp: ['S9'], ok: ['S8'], cat: 'Numbers (number cell)' },
  { q: 'orwell 1984', exp: ['S9'], ok: ['S8'], cat: 'Author+title' },
  { q: '1984 by George Orwell', exp: ['S9'], ok: ['S8'], cat: 'Author+title' },
  { q: 'is 1984 banned', exp: ['S9'], ok: ['S8'], cat: 'Question-style' },
  { q: 'nineteen eighty-four', exp: ['S9'], cat: 'Numbers (words)' },
  { q: '1984 dvd study guide', exp: ['S8'], ok: ['S9'], cat: 'Titles' },
  { q: '１９８４', exp: ['S9'], ok: ['S8'], cat: 'Unicode (full-width digits)' },
  { q: '١٩٨٤', exp: ['S9'], ok: ['S8'], cat: 'Unicode (Arabic-Indic digits)' },
  { q: 'thirteen little blue envelopes', exp: ['S7'], cat: 'Numbers (words)' },
  { q: '13', exp: ['S7'], cat: 'Short numeric' },
  { q: '13 envelopes', exp: ['S7'], cat: 'Short numeric' },
  { q: 'ten minute plays', exp: ['S11'], cat: 'Numbers + hyphen' },
  { q: '10-minute plays for teens volume 1', exp: ['S11'], cat: 'Numbers + hyphen' },
  { q: 'twenty ten-minute plays', exp: ['S11'], cat: 'Numbers (words)' },
  { q: '20', exp: ['S11'], cat: 'Short numeric' },
  { q: '2001 user guide', exp: ['S12'], cat: 'Titles' },
  { q: 'world book 2001', exp: ['S12'], cat: 'Order' },
  { q: 'two thousand one user guide', exp: ['S12'], cat: 'Numbers (words)' },
  { q: 'world book', exp: ['S12'], ok: ['S5'], cat: 'Flood (book)' },
  { q: 'things a boy can do', exp: ['S13'], cat: 'Partial title' },
  { q: '30 days', exp: ['S14'], cat: 'Titles' },
  { q: 'thirty days dvd', exp: ['S14'], ok: ['S8'], cat: 'Format word' },
  { q: '360 & more fairy tales', exp: ['S15'], cat: 'Ampersand' },
  { q: 'fairy tale', exp: ['S15'], cat: 'Plural' },
  { q: 'fairytales', exp: ['S15'], cat: 'Compounds' },
  { q: '500 nations', exp: ['S17'], cat: 'Titles' },
  { q: 'five hundred nations dvd', exp: ['S17'], ok: ['S8'], cat: 'Numbers (words) + format' },
  { q: 'sixty seconds to shine vol. 2', exp: ['S18'], cat: 'Volume labels' },
  { q: '60 seconds to shine volume ii', exp: ['S18'], cat: 'Roman numerals' },
  { q: 'one minute monologues for women', exp: ['S18'], cat: 'Hyphen + numbers' },
  { q: 'monologue for woman', exp: ['S18'], cat: 'Plural/singular' },
  { q: '7th knot', exp: ['S20'], ok: ['S19'], cat: 'Ordinals' },
  { q: 'lemony snicket book 3', exp: ['S21'], cat: 'Series' },
  { q: 'wide window book three', exp: ['S21'], cat: 'Series' },
  { q: 'The Wide Window (A Series of Unfortunate Events, #3)', exp: ['S21'], cat: 'Series (Goodreads)' },
  { q: 'unfortunate events bk 3', exp: ['S21'], cat: 'Series' },
  { q: '"wide window"', exp: ['S21'], cat: 'Quotes' },
  { q: 'aarons hair', exp: ['S22'], cat: 'Apostrophes' },
  { q: 'aaron’s hair', exp: ['S22'], cat: 'Apostrophes (curly)' },
  { q: "aaron's hair", exp: ['S22'], cat: 'Apostrophes' },
  { q: 'aaron', exp: ['S22', 'S23'], cat: 'Apostrophes' },
  { q: 'aarons magic village', exp: ['S23'], cat: 'Apostrophes' },
  { q: '101 stories of grandmother', exp: ['S5'], ok: ['S4', 'S6'], cat: 'Compounds' },
  { q: 'grandmother stories', exp: ['S5'], cat: 'Compounds' },
  { q: 'grand mother', exp: ['S5'], cat: 'Compounds' },
  { q: 'grandmothers stories', exp: ['S5'], cat: 'Compounds + plural' },
  { q: 'wacky science jokes', exp: ['S6'], ok: ['S4', 'O6'], cat: 'Titles' },
  { q: 'one hundred and one creepy jokes', exp: ['S4'], ok: ['S6'], cat: 'Numbers (words)' },
  { q: 'creepy joke', exp: ['S4'], ok: ['S6'], cat: 'Plural' },
  { q: '101', exp: ['S4', 'S5', 'S6'], cat: 'Numbers' },
  { q: 'jokes', exp: ['S4', 'S6'], cat: 'Titles' },
  { q: 'chicken soup for the soul', exp: ['S10'], cat: 'Truncated title in sheet' },
  { q: 'chicken soup for the teenage soul', exp: [], ok: ['S10'], cat: 'Similar title, other work' },
  { q: 'The 7 Habits of Highly Effective People', exp: [], ok: ['S19', 'S20'], cat: 'Similar title, other work' },
  { q: 'The 7 Habits of Highly Effective Teens: The Ultimate Teenage Success Guide', exp: ['S19'], ok: ['S20'], cat: 'Subtitle appended' },
  { q: 'Fahren­heit 451', exp: ['S16'], cat: 'Unicode (soft hyphen)' },
  { q: 'Fah​renheit 451', exp: ['S16'], cat: 'Unicode (zero-width)' },
  { q: 'fahrenheit 451; 7th knot', exp: ['S16', 'S20'], ok: ['S19'], cat: 'Semicolon (v1)' },
  // ---------- Other Materials ----------
  { q: 'don quixote', exp: ['O5'], cat: 'Titles' },
  { q: 'don quijote', exp: ['O5'], cat: 'Spelling variant' },
  { q: 'amplify ckla unit 7', exp: ['O6'], ok: ['O5', 'O7', 'O8'], cat: 'Series + number' },
  { q: 'Amplify CKLA - Unit 4', exp: ['O5'], ok: ['O6', 'O7', 'O8'], cat: 'Dash vs hyphen' },
  { q: 'ckla unit four', exp: ['O5'], ok: ['O6', 'O7', 'O8'], cat: 'Numbers (words)' },
  { q: 'science of breakable things', exp: ['O6'], cat: 'Titles' },
  { q: 'breakab', exp: ['O6'], cat: 'Typing (prefix)' },
  { q: 'renaissance', exp: ['O7', 'O8'], cat: 'Titles' },
  { q: 'renaissance reader', exp: ['O7'], ok: ['O8'], cat: 'Titles' },
  { q: 'patrons artists scholars', exp: ['O7'], cat: 'Punctuation' },
  { q: 'grade 5', exp: CKLA, cat: 'Grade labels' },
  { q: '5th grade ckla', exp: CKLA, cat: 'Grade labels' },
  { q: 'core knowledge language arts unit 4', exp: ['O5'], uns: true, cat: 'Acronym (alias needed)' },
  { q: 'it so happened', exp: ['O4'], cat: 'Short words' },
  { q: 'it so happened class viii', exp: ['O4'], cat: 'Roman numerals' },
  { q: 'supplementary english class 8', exp: ['O4'], cat: 'Typos in sheet' },
  { q: 'it', exp: ['O4'], cat: 'Short query' },
  // ---------- ISBN ----------
  { q: '979-8-89180-854-6', exp: ['O5'], cat: 'ISBN hyphenated' },
  { q: '9798891808546', exp: ['O5'], cat: 'ISBN' },
  { q: '979 8891 808546', exp: ['O5'], cat: 'ISBN spaced' },
  { q: 'ISBN 979-8-89180-854-6', exp: ['O5'], cat: 'ISBN with label' },
  { q: 'ISBN: 9798891808546', exp: ['O5'], cat: 'ISBN with label' },
  { q: '8174508355', exp: ['O4'], cat: 'ISBN-10' },
  { q: '81-7450-835-X', exp: ['O4'], cat: 'ISBN-10 with X' },
  { q: '978-81-7450-835-5', exp: ['O4'], cat: 'ISBN-13 of an ISBN-10 row' },
  { q: '9798891808', exp: ['O5'], ok: ['O6', 'O8'], cat: 'ISBN while typing (10 digits)' },
  { q: '979-8-89180-85', exp: ['O5'], ok: ['O6', 'O8'], cat: 'ISBN while typing (11 digits)' },
  { q: '979889180854', exp: ['O5'], cat: 'ISBN while typing (12 digits)' },
  // ---------- Memo ----------
  { q: '751459', exp: ['S21'], cat: 'Memo number' },
  // ---------- Things that should not flood ----------
  { q: 'harry potter', exp: [], cat: 'Not listed' },
  { q: 'the jungle book', exp: [], cat: 'Not listed (flood: book)' },
  { q: 'the book thief', exp: [], cat: 'Not listed (flood: book)' },
  { q: 'the hunger games', exp: [], cat: 'Not listed' },
  { q: 'diary of a wimpy kid', exp: [], cat: 'Not listed' },
  { q: 'the art of war', exp: [], cat: 'Not listed' },
  { q: '2010: odyssey two', exp: [], cat: 'Not listed (flood: year)' },
  { q: 'ministry of truth', exp: [], cat: 'Not listed (flood: Banned By)' },
  { q: 'the giver', exp: [], cat: 'Not listed' },
  { q: 'wonder', exp: [], cat: 'Not listed' },
  { q: 'library', exp: [], cat: 'Notes box must not match' },
  { q: 'blue', exp: ['S7'], cat: 'Notes box must not match' },
  { q: 'al', exp: [], cat: 'Short query (Et Al)' },
  { q: 'so', exp: [], ok: ['O4', 'S10'], cat: 'Typing (2 letters)' },
  { q: 'fa', exp: [], ok: ['S15', 'S16'], cat: 'Typing (2 letters)' },
  { q: '7', exp: ['S19', 'S20'], enter: true, cat: '1 char on Enter' },
  { q: 'kes', exp: [], ok: ['S5'], cat: 'Banned By code' },
  { q: 'ministry', exp: [], ok: MIN, cat: 'Banned By word' },
  { q: 'harry pot*', exp: [], cat: 'Wildcard habit' },
  // ---------- Extra probes (added after reading baseline) ----------
  { q: 'grade 8 english', exp: ['O4'], cat: 'Label+number pairs' },
  { q: 'ckla unit 5', exp: [], ok: CKLA, cat: 'Label+number pairs (no unit 5 listed)' },
  { q: 'unit 8 renaissance', exp: ['O7', 'O8'], cat: 'Label+number pairs' },
  { q: 'book 3', exp: ['S21'], cat: 'Label+number pairs' },
  { q: 'volume one', exp: ['S11'], cat: 'Label+number pairs' },
  { q: '8th class', exp: ['O4'], cat: 'Label+number pairs' },
  { q: 'Orwell, G. (1949). Nineteen eighty-four. Secker & Warburg.', exp: ['S9'], ok: ['S8'], cat: 'Pasted citation' },
  { q: 'Nineteen Eighty-Four by George Orwell (Penguin Modern Classics)', exp: ['S9'], ok: ['S8'], cat: 'Pasted listing' },
  { q: 'Fahr­en­heit 451 Brad­bury', exp: ['S16'], cat: 'Unicode (several soft hyphens)' },
  { q: 'Fahrenheit 451 ISBN 978-1-4516-7331-9', exp: ['S16'], cat: 'Pasted listing with hyphenated ISBN' },
  { q: 'shine', exp: [], ok: ['S18'], cat: 'Real word 1 edit from an author (Stine)' },
  { q: 'thirteen reasons why', exp: [], ok: ['S7'], cat: 'Not listed (shares 13)' },
  { q: 'two eleven things', exp: ['S13'], cat: 'Numbers (spoken digit groups)' },
];
module.exports = { Q };
